// Generated from data/atlas/*.csv by build.py. Edit the CSVs, not this file.
window.ATLAS_DATA = {
  "domains": [
    {
      "ID": "D-001",
      "Name": "Current Mission",
      "Type": "Mission",
      "Program category": "",
      "Purpose": "Revolutionary social and political change around AI governance.",
      "Parent ID": "",
      "Circle ID": "G-001",
      "Status": "Planned",
      "Stage": "Ideated",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": ""
    },
    {
      "ID": "D-002",
      "Name": "Advocacy",
      "Type": "Pillar",
      "Program category": "",
      "Purpose": "Pillars of support—civil society institutions, politicians, and media—become supporters.",
      "Parent ID": "D-001",
      "Circle ID": "",
      "Status": "Active",
      "Stage": "In Progress",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "Converts public pressure into binding policy",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": ""
    },
    {
      "ID": "D-003",
      "Name": "Community",
      "Type": "Pillar",
      "Program category": "",
      "Purpose": "Large numbers of people participate as active supporters.",
      "Parent ID": "D-001",
      "Circle ID": "",
      "Status": "Planned",
      "Stage": "Approved",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "Scales the movement beyond the founding team",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": ""
    },
    {
      "ID": "D-004",
      "Name": "Empowerment",
      "Type": "Pillar",
      "Program category": "",
      "Purpose": "Abundant leadership within the movement.",
      "Parent ID": "D-001",
      "Circle ID": "",
      "Status": "Active",
      "Stage": "In Progress",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "Builds the volunteer capacity everything else depends on",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": ""
    },
    {
      "ID": "D-005",
      "Name": "Stop 1984",
      "Type": "Product/Service",
      "Program category": "",
      "Purpose": "End AI-enabled mass surveillance.",
      "Parent ID": "D-033",
      "Circle ID": "",
      "Status": "Active",
      "Stage": "In Progress",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "First proof point: local win building toward statewide policy",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": ""
    },
    {
      "ID": "D-006",
      "Name": "Chapters",
      "Type": "Program",
      "Program category": "",
      "Purpose": "Passive supporters become Members by connecting locally.",
      "Parent ID": "D-003",
      "Circle ID": "",
      "Status": "Planned",
      "Stage": "Proposed",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "Distributed growth engine",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": ""
    },
    {
      "ID": "D-007",
      "Name": "Global Fellowship",
      "Type": "Product/Service",
      "Program category": "",
      "Purpose": "Members, regardless of location, can contribute meaningfully to movement infrastructure.",
      "Parent ID": "D-038",
      "Circle ID": "",
      "Status": "Active",
      "Stage": "In Progress",
      "Started on": "",
      "Ended on": "",
      "Key Features": "Semester cohorts, 1 project/Fellow, kickoff + coworking sessions, 3 exit paths",
      "User": "Volunteers seeking high-ownership involvement",
      "Value Proposition": "Turns motivated volunteers into skilled, accountable contributors in one semester",
      "SOP URL": "",
      "SOP Notes": "Exists — Fellowship Handbook",
      "Ownership note": ""
    },
    {
      "ID": "D-008",
      "Name": "Training",
      "Type": "Product/Service",
      "Program category": "",
      "Purpose": "Knowledge spreads throughout Members and Fellows.",
      "Parent ID": "D-037",
      "Circle ID": "",
      "Status": "Planned",
      "Stage": "Ideated",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "Two-Year Roadmap commitment; not yet started",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": ""
    },
    {
      "ID": "D-009",
      "Name": "Communications",
      "Type": "Program",
      "Program category": "",
      "Purpose": "People understand the movement and stay engaged.",
      "Parent ID": "D-003",
      "Circle ID": "",
      "Status": "Active",
      "Stage": "In Progress",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "Serves all three pillars, not one campaign",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": ""
    },
    {
      "ID": "D-010",
      "Name": "Finance & Fundraising",
      "Type": "Program",
      "Program category": "",
      "Purpose": "Movement has the money to execute its strategy.",
      "Parent ID": "D-031",
      "Circle ID": "",
      "Status": "Active",
      "Stage": "In Progress",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "Funds runway for everything above",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": ""
    },
    {
      "ID": "D-011",
      "Name": "Operations & Infrastructure",
      "Type": "Program",
      "Program category": "Enabling",
      "Purpose": "Systems that let a lean team run at scale",
      "Parent ID": "D-001",
      "Circle ID": "",
      "Status": "Active",
      "Stage": "In Progress",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "Removes the founder as a bottleneck",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": ""
    },
    {
      "ID": "D-012",
      "Name": "Media Program",
      "Type": "Product/Service",
      "Program category": "",
      "Purpose": "Ongoing press/spokesperson capability usable by any campaign",
      "Parent ID": "D-009",
      "Circle ID": "G-004",
      "Status": "Planned",
      "Stage": "Proposed",
      "Started on": "",
      "Ended on": "",
      "Key Features": "Media moments, journalist relationships, press kit, spokesperson training, visual identity bank",
      "User": "Press, public, prospective members",
      "Value Proposition": "Converts campaign wins into public visibility that accelerates recruitment",
      "SOP URL": "",
      "SOP Notes": "Missing",
      "Ownership note": ""
    },
    {
      "ID": "D-013",
      "Name": "Website",
      "Type": "Product/Service",
      "Program category": "",
      "Purpose": "Visitors understand the movement and know how to participate.",
      "Parent ID": "D-009",
      "Circle ID": "G-004",
      "Status": "Active",
      "Stage": "In Progress",
      "Started on": "",
      "Ended on": "",
      "Key Features": "Campaign pages, strategy page, donate page",
      "User": "All external visitors",
      "Value Proposition": "Primary conversion and credibility surface",
      "SOP URL": "",
      "SOP Notes": "Missing",
      "Ownership note": ""
    },
    {
      "ID": "D-014",
      "Name": "Resource Center",
      "Type": "Product/Service",
      "Program category": "",
      "Purpose": "Social movement resources and know-how are clear and accessible.",
      "Parent ID": "D-037",
      "Circle ID": "",
      "Status": "Active",
      "Stage": "In Progress",
      "Started on": "",
      "Ended on": "",
      "Key Features": "Wiki.js base, information architecture, contribution/permission rules",
      "User": "All Fellows, organizers, chapter leaders",
      "Value Proposition": "Lets the org scale past founder-memory",
      "SOP URL": "",
      "SOP Notes": "In progress — this IS the SOP system",
      "Ownership note": ""
    },
    {
      "ID": "D-015",
      "Name": "Membership Registration & Onboarding",
      "Type": "Product/Service",
      "Program category": "",
      "Purpose": "Supporters can easily join and start participating.",
      "Parent ID": "D-036",
      "Circle ID": "",
      "Status": "Active",
      "Stage": "In Progress",
      "Started on": "",
      "Ended on": "",
      "Key Features": "Stripe + CRM + Discord integration, onboarding/offboarding automation",
      "User": "Dues-paying members (M2+)",
      "Value Proposition": "Reliable, low-labor pipeline from interested to active member",
      "SOP URL": "",
      "SOP Notes": "Missing",
      "Ownership note": ""
    },
    {
      "ID": "D-016",
      "Name": "House Party Fundraising Kit",
      "Type": "Product/Service",
      "Program category": "",
      "Purpose": "Turnkey fundraiser-hosting kit",
      "Parent ID": "D-010",
      "Circle ID": "",
      "Status": "Planned",
      "Stage": "Proposed",
      "Started on": "",
      "Ended on": "",
      "Key Features": "Invitation templates, host guide, ask script, donation page, automated follow-up",
      "User": "Supporter-hosts running small fundraisers",
      "Value Proposition": "Multiplies fundraising capacity without staff presence",
      "SOP URL": "",
      "SOP Notes": "Missing",
      "Ownership note": ""
    },
    {
      "ID": "D-017",
      "Name": "Social Media",
      "Type": "Product/Service",
      "Program category": "",
      "Purpose": "People encounter, follow, and share the movement.",
      "Parent ID": "D-009",
      "Circle ID": "",
      "Status": "Planned",
      "Stage": "Proposed",
      "Started on": "",
      "Ended on": "",
      "Key Features": "Repeatable content workflow, scheduling automation, measurement",
      "User": "Broader public, prospective supporters",
      "Value Proposition": "Compounding reach at low marginal cost",
      "SOP URL": "",
      "SOP Notes": "Missing",
      "Ownership note": ""
    },
    {
      "ID": "D-018",
      "Name": "Newspaper",
      "Type": "Product/Service",
      "Program category": "",
      "Purpose": "Members stay informed, connected, and engaged.",
      "Parent ID": "D-036",
      "Circle ID": "",
      "Status": "Active",
      "Stage": "In Progress",
      "Started on": "",
      "Ended on": "",
      "Key Features": "Recurring sections, submission process, editorial workflow",
      "User": "Members & movement readers",
      "Value Proposition": "Builds durable voice; low-barrier way for Fellows to contribute writing",
      "SOP URL": "",
      "SOP Notes": "Missing — Jan launch target",
      "Ownership note": ""
    },
    {
      "ID": "D-019",
      "Name": "Start a Circle",
      "Type": "Product/Service",
      "Program category": "",
      "Purpose": "Members can easily start local groups.",
      "Parent ID": "D-006",
      "Circle ID": "",
      "Status": "Planned",
      "Stage": "Proposed",
      "Started on": "",
      "Ended on": "",
      "Key Features": "Constitution, lifecycle model, Discord architecture, leader onboarding",
      "User": "Local organizers starting a chapter",
      "Value Proposition": "Lets the movement scale to hundreds of chapters without a central bottleneck",
      "SOP URL": "",
      "SOP Notes": "Missing",
      "Ownership note": ""
    },
    {
      "ID": "D-020",
      "Name": "General Meetings",
      "Type": "Product/Service",
      "Program category": "",
      "Purpose": "Recurring member-facing convening (not a Holacracy governance meeting)",
      "Parent ID": "D-001",
      "Circle ID": "",
      "Status": "Active",
      "Stage": "In Progress",
      "Started on": "",
      "Ended on": "",
      "Key Features": "Recurring cadence, prepped content/questions, breakout rooms, Discord announcement",
      "User": "Members & supporters, all engagement levels",
      "Value Proposition": "Regular touchpoint that builds belonging and surfaces org news",
      "SOP URL": "",
      "SOP Notes": "Partial — steps exist in Active Projects, not written up",
      "Ownership note": ""
    },
    {
      "ID": "D-021",
      "Name": "1-1s",
      "Type": "Product/Service",
      "Program category": "",
      "Purpose": "Relational check-ins outside formal governance process",
      "Parent ID": "D-001",
      "Circle ID": "",
      "Status": "Active",
      "Stage": "In Progress",
      "Started on": "",
      "Ended on": "",
      "Key Features": "Regular founder/lead check-ins, onboarding, mentorship",
      "User": "Fellows, new members, prospective leaders/donors",
      "Value Proposition": "High-touch trust-building that async channels can't replicate",
      "SOP URL": "",
      "SOP Notes": "Missing",
      "Ownership note": "Needs clarification: Vision Steward / relevant Circle Lead"
    },
    {
      "ID": "D-022",
      "Name": "Freeze AI Campaign",
      "Type": "Product/Service",
      "Program category": "",
      "Purpose": "",
      "Parent ID": "D-033",
      "Circle ID": "",
      "Status": "Needs definition",
      "Stage": "",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": "Added 2026-09-22 per governance restructuring; Purpose/Stage not yet specified."
    },
    {
      "ID": "D-023",
      "Name": "No Killer Robots",
      "Type": "Product/Service",
      "Program category": "",
      "Purpose": "Regulate deadly autonomous weapons.",
      "Parent ID": "D-033",
      "Circle ID": "",
      "Status": "Needs definition",
      "Stage": "",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": "Added 2026-09-22 per governance restructuring; Purpose/Stage not yet specified."
    },
    {
      "ID": "D-024",
      "Name": "Stop 1984! Background Research",
      "Type": "Project",
      "Program category": "",
      "Purpose": "",
      "Parent ID": "D-005",
      "Circle ID": "",
      "Status": "Needs definition",
      "Stage": "",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": "Added 2026-09-22 per governance restructuring; owned by Background Researcher (G-037)."
    },
    {
      "ID": "D-025",
      "Name": "Freeze AI Background Research",
      "Type": "Project",
      "Program category": "",
      "Purpose": "",
      "Parent ID": "D-022",
      "Circle ID": "",
      "Status": "Needs definition",
      "Stage": "",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": "Added 2026-09-22 per governance restructuring; owned by Background Researcher (G-037)."
    },
    {
      "ID": "D-026",
      "Name": "Stop 1984! Asks",
      "Type": "Project",
      "Program category": "",
      "Purpose": "",
      "Parent ID": "D-005",
      "Circle ID": "",
      "Status": "Needs definition",
      "Stage": "",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": "Added 2026-09-22 per governance restructuring; owned by Policy Ask Creator (G-038)."
    },
    {
      "ID": "D-027",
      "Name": "Freeze AI Asks",
      "Type": "Project",
      "Program category": "",
      "Purpose": "",
      "Parent ID": "D-022",
      "Circle ID": "",
      "Status": "Needs definition",
      "Stage": "",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": "Added 2026-09-22 per governance restructuring; owned by Policy Ask Creator (G-038)."
    },
    {
      "ID": "D-028",
      "Name": "No Killer Robots Policy",
      "Type": "Project",
      "Program category": "",
      "Purpose": "",
      "Parent ID": "D-023",
      "Circle ID": "",
      "Status": "Needs definition",
      "Stage": "",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": "Added 2026-09-22 per governance restructuring; owned by No Killer Robots Owner (G-039)."
    },
    {
      "ID": "D-029",
      "Name": "Campaign Strategy",
      "Type": "Project",
      "Program category": "",
      "Purpose": "",
      "Parent ID": "D-034",
      "Circle ID": "",
      "Status": "Needs definition",
      "Stage": "",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": "Added 2026-09-22 per governance restructuring; owned by Campaign Strategist (G-040)."
    },
    {
      "ID": "D-030",
      "Name": "Stop 1984! Campaign Design",
      "Type": "Project",
      "Program category": "",
      "Purpose": "",
      "Parent ID": "D-005",
      "Circle ID": "G-004",
      "Status": "Needs definition",
      "Stage": "",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": "Added 2026-09-22 per governance restructuring; held undelegated by Media Circle (G-004), no specific role named."
    },
    {
      "ID": "D-031",
      "Name": "Meta",
      "Type": "Pillar",
      "Program category": "",
      "Purpose": "Movement has a vision, strategy, and financial support.",
      "Parent ID": "D-001",
      "Circle ID": "",
      "Status": "Needs definition",
      "Stage": "",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": ""
    },
    {
      "ID": "D-032",
      "Name": "Vision & Strategy",
      "Type": "Program",
      "Program category": "",
      "Purpose": "Movement has a clear vision and strategy.",
      "Parent ID": "D-031",
      "Circle ID": "",
      "Status": "Needs definition",
      "Stage": "",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": ""
    },
    {
      "ID": "D-033",
      "Name": "Campaign Creation",
      "Type": "Program",
      "Program category": "",
      "Purpose": "Build priority campaigns.",
      "Parent ID": "D-002",
      "Circle ID": "",
      "Status": "Needs definition",
      "Stage": "",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": ""
    },
    {
      "ID": "D-034",
      "Name": "Campaign Support",
      "Type": "Program",
      "Program category": "",
      "Purpose": "Campaigns have what they need to succeed.",
      "Parent ID": "D-002",
      "Circle ID": "",
      "Status": "Needs definition",
      "Stage": "",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": ""
    },
    {
      "ID": "D-035",
      "Name": "Campaign Execution Toolkit",
      "Type": "Product/Service",
      "Program category": "",
      "Purpose": "Organizers have the tools to run effective campaigns.",
      "Parent ID": "D-034",
      "Circle ID": "",
      "Status": "Needs definition",
      "Stage": "",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": ""
    },
    {
      "ID": "D-036",
      "Name": "Global Membership",
      "Type": "Program",
      "Program category": "",
      "Purpose": "Passive supporters anywhere have a way to deepen their commitment.",
      "Parent ID": "D-003",
      "Circle ID": "",
      "Status": "Needs definition",
      "Stage": "",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": ""
    },
    {
      "ID": "D-037",
      "Name": "Knowledge",
      "Type": "Program",
      "Program category": "",
      "Purpose": "Members know why and how to participate.",
      "Parent ID": "D-004",
      "Circle ID": "",
      "Status": "Needs definition",
      "Stage": "",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": ""
    },
    {
      "ID": "D-038",
      "Name": "Development",
      "Type": "Program",
      "Program category": "",
      "Purpose": "Members are empowered to take over projects and domains.",
      "Parent ID": "D-004",
      "Circle ID": "",
      "Status": "Needs definition",
      "Stage": "",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": ""
    },
    {
      "ID": "D-039",
      "Name": "Governance",
      "Type": "Program",
      "Program category": "",
      "Purpose": "Clear structure and roles for all Fellows & Staff.",
      "Parent ID": "D-004",
      "Circle ID": "",
      "Status": "Needs definition",
      "Stage": "",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": ""
    },
    {
      "ID": "D-040",
      "Name": "Role Management",
      "Type": "Product/Service",
      "Program category": "",
      "Purpose": "Fellows hold domains that suit their strengths.",
      "Parent ID": "D-039",
      "Circle ID": "",
      "Status": "Needs definition",
      "Stage": "",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": ""
    },
    {
      "ID": "D-041",
      "Name": "Project Management",
      "Type": "Product/Service",
      "Program category": "",
      "Purpose": "Teams break down and strategically prioritize projects within each domain.",
      "Parent ID": "D-039",
      "Circle ID": "",
      "Status": "Needs definition",
      "Stage": "",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": ""
    }
  ],
  "governance": [
    {
      "ID": "G-001",
      "Name": "Sapiens First Global",
      "Type": "Circle",
      "Parent Circle ID": "",
      "Purpose": "A world where AI serves the common good",
      "Accountabilities": "",
      "Scope": "",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Rohan",
      "Person ID": "",
      "Definition note": ""
    },
    {
      "ID": "G-002",
      "Name": "Vision & Strategy",
      "Type": "Role",
      "Parent Circle ID": "G-041",
      "Purpose": "Cross-pillar strategic planning; Keep the org anchored to Purpose over time",
      "Accountabilities": "Setting/tracking OKRs; surfacing what's slipping; sequencing priority-city rankings; Reviewing major strategic decisions against Purpose; resolving Purpose-level tensions",
      "Scope": "Org-wide OKRs, quarterly priorities; Final call on Purpose/Vision statements",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Rohan",
      "Person ID": "",
      "Definition note": "Parent circle changed from General Company Circle (G-001) to Vision & Strategy Circle (G-003) per 2026-09-22 governance restructuring. Merged with G-003 on 2026-09-23; continuing role retains its ID and work ownership. Purpose, accountabilities, scope, privileges, and recorded assignment carried forward from the wrapper."
    },
    {
      "ID": "G-003",
      "Name": "Vision & Strategy",
      "Type": "Circle",
      "Parent Circle ID": "G-001",
      "Purpose": "Cross-pillar strategic planning",
      "Accountabilities": "Setting/tracking OKRs; surfacing what's slipping; sequencing priority-city rankings",
      "Scope": "Org-wide OKRs, quarterly priorities",
      "Privileges": "",
      "Status": "Retired",
      "Lead Link": "Rohan",
      "Person ID": "",
      "Definition note": "Renamed from Strategy Circle on 2026-09-22. Retired 2026-09-23: single-role circle consolidated into G-002; see the dated succeeds relationship."
    },
    {
      "ID": "G-004",
      "Name": "Media",
      "Type": "Circle",
      "Parent Circle ID": "G-001",
      "Purpose": "Own how Sapiens First is seen and heard externally",
      "Accountabilities": "Maintaining visual identity; approving public statements; managing press",
      "Scope": "Brand, external messaging, website content",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Unassigned",
      "Person ID": "",
      "Definition note": "Renamed from Communications & Narrative Circle on 2026-09-22."
    },
    {
      "ID": "G-005",
      "Name": "Spokesperson",
      "Type": "Role",
      "Parent Circle ID": "G-004",
      "Purpose": "Represent Sapiens First publicly with a consistent voice",
      "Accountabilities": "Media training; interview prep; approving quotes attributed to the org",
      "Scope": "Public statements, media interviews",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Unassigned",
      "Person ID": "",
      "Definition note": ""
    },
    {
      "ID": "G-006",
      "Name": "Website Owner",
      "Type": "Role",
      "Parent Circle ID": "G-004",
      "Purpose": "Keep sapiensfirst.org accurate and converting",
      "Accountabilities": "Publishing updates; maintaining donate/strategy/campaign pages",
      "Scope": "Site content, structure, hosting",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Unassigned",
      "Person ID": "",
      "Definition note": ""
    },
    {
      "ID": "G-007",
      "Name": "Advocacy",
      "Type": "Circle",
      "Parent Circle ID": "G-001",
      "Purpose": "Win policy that restricts AI-enabled harm",
      "Accountabilities": "Choosing campaigns; setting policy platform; coalition strategy",
      "Scope": "Campaign selection, policy asks",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Unassigned",
      "Person ID": "",
      "Definition note": ""
    },
    {
      "ID": "G-008",
      "Name": "Stop 1984!",
      "Type": "Circle",
      "Parent Circle ID": "G-007",
      "Purpose": "Ban AI-enabled mass surveillance, starting in California",
      "Accountabilities": "Research library; policy platform; city-by-city strategic plan; media resources",
      "Scope": "Campaign research, asks, media, strategic plan",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Alex",
      "Person ID": "",
      "Definition note": ""
    },
    {
      "ID": "G-009",
      "Name": "California Strategy",
      "Type": "Role",
      "Parent Circle ID": "G-008",
      "Purpose": "Sequence the CA campaign for winnable early victories",
      "Accountabilities": "Ranking target cities; mapping stakeholders; drafting city playbooks",
      "Scope": "Priority-city rankings, coalition map",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Alex",
      "Person ID": "",
      "Definition note": ""
    },
    {
      "ID": "G-010",
      "Name": "Community",
      "Type": "Circle",
      "Parent Circle ID": "G-001",
      "Purpose": "Build a nationwide network of local chapters",
      "Accountabilities": "Chapter lifecycle; member onboarding/offboarding; digital presence",
      "Scope": "Chapter model, member engagement, social content",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Unassigned",
      "Person ID": "",
      "Definition note": ""
    },
    {
      "ID": "G-011",
      "Name": "Chapter Network",
      "Type": "Circle",
      "Parent Circle ID": "G-010",
      "Purpose": "Make starting/running a chapter easy and safe",
      "Accountabilities": "Starter kit; leader vetting; dispute handling; chapter lifecycle management",
      "Scope": "Chapter constitution, Discord architecture",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Unassigned",
      "Person ID": "",
      "Definition note": ""
    },
    {
      "ID": "G-012",
      "Name": "Digital Presence",
      "Type": "Circle",
      "Parent Circle ID": "G-010",
      "Purpose": "Grow reach across social channels",
      "Accountabilities": "Content production workflow; approval process; channel metrics",
      "Scope": "Content calendar, scheduling automations",
      "Privileges": "",
      "Status": "Retired",
      "Lead Link": "Unassigned",
      "Person ID": "",
      "Definition note": " Retired 2026-09-23: single-role circle consolidated into G-033; see the dated succeeds relationship."
    },
    {
      "ID": "G-013",
      "Name": "Empowerment",
      "Type": "Circle",
      "Parent Circle ID": "G-001",
      "Purpose": "Train and onboard leaders/activists at scale",
      "Accountabilities": "Cohort management; curriculum; leadership academy",
      "Scope": "Fellowship program, leadership curriculum",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Unassigned",
      "Person ID": "",
      "Definition note": ""
    },
    {
      "ID": "G-014",
      "Name": "Fellowship Program",
      "Type": "Circle",
      "Parent Circle ID": "G-013",
      "Purpose": "Run the Fellowship end-to-end",
      "Accountabilities": "Applicant funnel; project matching; check-ins; offboarding",
      "Scope": "Recruitment, matching, cohort management",
      "Privileges": "",
      "Status": "Retired",
      "Lead Link": "Unassigned",
      "Person ID": "",
      "Definition note": " Retired 2026-09-23: single-role circle consolidated into G-026; see the dated succeeds relationship."
    },
    {
      "ID": "G-015",
      "Name": "Knowledge Base",
      "Type": "Circle",
      "Parent Circle ID": "G-036",
      "Purpose": "Centralize organizational knowledge",
      "Accountabilities": "Content ownership rules; permissions; keeping content current",
      "Scope": "Wiki.js, information architecture",
      "Privileges": "",
      "Status": "Retired",
      "Lead Link": "Damian",
      "Person ID": "",
      "Definition note": "Parent circle changed from Empowerment Circle (G-013) to Tech Circle (G-036) per 2026-09-22 governance restructuring: Tech owns knowledge management. Retired 2026-09-23: single-role circle consolidated into G-030; see the dated succeeds relationship."
    },
    {
      "ID": "G-016",
      "Name": "Newspaper",
      "Type": "Circle",
      "Parent Circle ID": "G-013",
      "Purpose": "Publish the Sapiens First Newspaper",
      "Accountabilities": "Submissions process; editorial standards; production cadence",
      "Scope": "Editorial voice, sections, production",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Victoria",
      "Person ID": "",
      "Definition note": ""
    },
    {
      "ID": "G-017",
      "Name": "Biz Ops",
      "Type": "Circle",
      "Parent Circle ID": "G-001",
      "Purpose": "Systems that let a lean team run at scale",
      "Accountabilities": "Campaign automations; data integrity; 501(c)(3)/(c)(4) compliance; budget tracking",
      "Scope": "CRM, automations, legal/compliance, finance",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Unassigned",
      "Person ID": "",
      "Definition note": "Renamed from Operations & Infrastructure Circle on 2026-09-22."
    },
    {
      "ID": "G-018",
      "Name": "Membership Systems",
      "Type": "Circle",
      "Parent Circle ID": "G-017",
      "Purpose": "Automate the member lifecycle",
      "Accountabilities": "Onboarding/offboarding triggers; failure handling; privacy/backups",
      "Scope": "Stripe, CRM, Discord integration",
      "Privileges": "",
      "Status": "Retired",
      "Lead Link": "Baisayan",
      "Person ID": "",
      "Definition note": " Retired 2026-09-23: single-role circle consolidated into G-031; see the dated succeeds relationship."
    },
    {
      "ID": "G-019",
      "Name": "Finance & Fundraising",
      "Type": "Circle",
      "Parent Circle ID": "G-041",
      "Purpose": "Fund the org's runway",
      "Accountabilities": "Prospect pipeline; grant reporting; Founder's Council program; House Party kit",
      "Scope": "Major gifts, foundations, dues, events",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Unassigned",
      "Person ID": "",
      "Definition note": "Renamed from Fundraising & Development Circle on 2026-09-22."
    },
    {
      "ID": "G-020",
      "Name": "House Party Program",
      "Type": "Role",
      "Parent Circle ID": "G-019",
      "Purpose": "Turn supporters into fundraising hosts",
      "Accountabilities": "Host recruitment; kit iteration; donation tracking",
      "Scope": "Host kit, event follow-up automation",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Peter",
      "Person ID": "",
      "Definition note": ""
    },
    {
      "ID": "G-021",
      "Name": "Advocacy Circle Lead",
      "Type": "Role",
      "Parent Circle ID": "G-007",
      "Purpose": "",
      "Accountabilities": "",
      "Scope": "",
      "Privileges": "",
      "Status": "Needs definition",
      "Lead Link": "",
      "Person ID": "",
      "Definition note": "Named as an owner in the original work register; no matching governance definition. Original label: Advocacy Circle Lead. Parent circle set to Advocacy Circle (G-007): exact name match."
    },
    {
      "ID": "G-022",
      "Name": "Community Circle Lead",
      "Type": "Role",
      "Parent Circle ID": "G-010",
      "Purpose": "",
      "Accountabilities": "",
      "Scope": "",
      "Privileges": "",
      "Status": "Needs definition",
      "Lead Link": "",
      "Person ID": "",
      "Definition note": "Named as an owner in the original work register; no matching governance definition. Original label: Community Circle Lead. Parent circle set to Community Circle (G-010): exact name match."
    },
    {
      "ID": "G-023",
      "Name": "Empowerment Circle Lead",
      "Type": "Role",
      "Parent Circle ID": "G-013",
      "Purpose": "",
      "Accountabilities": "",
      "Scope": "",
      "Privileges": "",
      "Status": "Needs definition",
      "Lead Link": "",
      "Person ID": "",
      "Definition note": "Named as an owner in the original work register; no matching governance definition. Original label: Empowerment Circle Lead. Parent circle set to Empowerment Circle (G-013): exact name match."
    },
    {
      "ID": "G-024",
      "Name": "Stop 1984! Circle Lead",
      "Type": "Role",
      "Parent Circle ID": "G-008",
      "Purpose": "",
      "Accountabilities": "",
      "Scope": "",
      "Privileges": "",
      "Status": "Needs definition",
      "Lead Link": "",
      "Person ID": "",
      "Definition note": "Named as an owner in the original work register; no matching governance definition. Original label: Stop 1984! Circle Lead (Alex). Parent circle set to Stop 1984! Circle (G-008): exact name match."
    },
    {
      "ID": "G-025",
      "Name": "Chapter Network Circle Lead",
      "Type": "Role",
      "Parent Circle ID": "G-011",
      "Purpose": "",
      "Accountabilities": "",
      "Scope": "",
      "Privileges": "",
      "Status": "Needs definition",
      "Lead Link": "",
      "Person ID": "",
      "Definition note": "Named as an owner in the original work register; no matching governance definition. Original label: Chapter Network Circle Lead. Parent circle set to Chapter Network Circle (G-011): exact name match."
    },
    {
      "ID": "G-026",
      "Name": "Fellowship Program",
      "Type": "Role",
      "Parent Circle ID": "G-013",
      "Purpose": "Run the Fellowship end-to-end",
      "Accountabilities": "Applicant funnel; project matching; check-ins; offboarding",
      "Scope": "Recruitment, matching, cohort management",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Unassigned",
      "Person ID": "",
      "Definition note": "Named as an owner in the original work register; no matching governance definition. Original label: Fellowship Program Lead. Parent circle set to Fellowship Program Circle (G-014): matching name. Merged with G-014 on 2026-09-23; continuing role retains its ID and work ownership. Purpose, accountabilities, scope, privileges, and recorded assignment carried forward from the wrapper."
    },
    {
      "ID": "G-027",
      "Name": "Marketing & Communications Circle Lead",
      "Type": "Role",
      "Parent Circle ID": "",
      "Purpose": "",
      "Accountabilities": "",
      "Scope": "",
      "Privileges": "",
      "Status": "Needs definition",
      "Lead Link": "",
      "Person ID": "",
      "Definition note": "Named as an owner in the original work register; no matching governance definition. Original label: Marketing & Communications Circle Lead. No governance circle named \"Marketing & Communications\" exists (closest is Communications & Narrative Circle, G-004); left unassigned pending explicit reconciliation, per the Website/Marketing & Communications naming mismatch already noted for D-013."
    },
    {
      "ID": "G-028",
      "Name": "Fundraising & Development Circle Lead",
      "Type": "Role",
      "Parent Circle ID": "G-019",
      "Purpose": "",
      "Accountabilities": "",
      "Scope": "",
      "Privileges": "",
      "Status": "Needs definition",
      "Lead Link": "",
      "Person ID": "",
      "Definition note": "Named as an owner in the original work register; no matching governance definition. Original label: Fundraising & Development Circle Lead. Parent circle set to Fundraising & Development Circle (G-019): exact name match."
    },
    {
      "ID": "G-029",
      "Name": "Operations & Infrastructure Circle Lead",
      "Type": "Role",
      "Parent Circle ID": "G-017",
      "Purpose": "",
      "Accountabilities": "",
      "Scope": "",
      "Privileges": "",
      "Status": "Needs definition",
      "Lead Link": "",
      "Person ID": "",
      "Definition note": "Named as an owner in the original work register; no matching governance definition. Original label: Operations & Infrastructure Circle Lead. Parent circle set to Operations & Infrastructure Circle (G-017): exact name match."
    },
    {
      "ID": "G-030",
      "Name": "Knowledge Base",
      "Type": "Role",
      "Parent Circle ID": "G-001",
      "Purpose": "Centralize organizational knowledge",
      "Accountabilities": "Content ownership rules; permissions; keeping content current",
      "Scope": "Wiki.js, information architecture",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Damian",
      "Person ID": "",
      "Definition note": "Named as an owner in the original work register; no matching governance definition. Original label: Knowledge Base Steward (Damian). Parent circle set to Knowledge Base Circle (G-015): matching name, corroborated by Damian also being its recorded Lead Link. Merged with G-015 on 2026-09-23; continuing role retains its ID and work ownership. Purpose, accountabilities, scope, privileges, and recorded assignment carried forward from the wrapper. Tech (G-036) also consolidated on 2026-09-23 after the Knowledge Base merge left it with only this role; no additional definition or assignment was inferred."
    },
    {
      "ID": "G-031",
      "Name": "Membership Systems",
      "Type": "Role",
      "Parent Circle ID": "G-017",
      "Purpose": "Automate the member lifecycle",
      "Accountabilities": "Onboarding/offboarding triggers; failure handling; privacy/backups",
      "Scope": "Stripe, CRM, Discord integration",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Baisayan",
      "Person ID": "",
      "Definition note": "Named as an owner in the original work register; no matching governance definition. Original label: Membership Systems Lead (Baisayan). Parent circle set to Membership Systems Circle (G-018): matching name, corroborated by Baisayan also being its recorded Lead Link. Merged with G-018 on 2026-09-23; continuing role retains its ID and work ownership. Purpose, accountabilities, scope, privileges, and recorded assignment carried forward from the wrapper."
    },
    {
      "ID": "G-032",
      "Name": "House Party Program Lead",
      "Type": "Role",
      "Parent Circle ID": "",
      "Purpose": "",
      "Accountabilities": "",
      "Scope": "",
      "Privileges": "",
      "Status": "Needs definition",
      "Lead Link": "",
      "Person ID": "",
      "Definition note": "Named as an owner in the original work register; no matching governance definition. Original label: House Party Program Lead (Peter). Possible duplicate of House Party Program (G-020, Role under G-019, Lead Link Peter); left unassigned pending explicit reconciliation rather than merged."
    },
    {
      "ID": "G-033",
      "Name": "Digital Presence",
      "Type": "Role",
      "Parent Circle ID": "G-010",
      "Purpose": "Grow reach across social channels",
      "Accountabilities": "Content production workflow; approval process; channel metrics",
      "Scope": "Content calendar, scheduling automations",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Unassigned",
      "Person ID": "",
      "Definition note": "Named as an owner in the original work register; no matching governance definition. Original label: Digital Presence Lead. Parent circle set to Digital Presence Circle (G-012): matching name. Merged with G-012 on 2026-09-23; continuing role retains its ID and work ownership. Purpose, accountabilities, scope, privileges, and recorded assignment carried forward from the wrapper."
    },
    {
      "ID": "G-034",
      "Name": "Editor-in-Chief",
      "Type": "Role",
      "Parent Circle ID": "",
      "Purpose": "",
      "Accountabilities": "",
      "Scope": "",
      "Privileges": "",
      "Status": "Needs definition",
      "Lead Link": "",
      "Person ID": "",
      "Definition note": "Named as an owner in the original work register; no matching governance definition. Original label: Editor-in-Chief (Victoria). Likely belongs under Newspaper Circle (G-016, Lead Link Victoria), but the name itself doesn't reference a circle; left unassigned pending explicit reconciliation."
    },
    {
      "ID": "G-035",
      "Name": "Secretary",
      "Type": "Role",
      "Parent Circle ID": "",
      "Purpose": "",
      "Accountabilities": "",
      "Scope": "",
      "Privileges": "",
      "Status": "Needs definition",
      "Lead Link": "",
      "Person ID": "",
      "Definition note": "Named as an owner in the original work register; no matching governance definition. Original label: Secretary. No corresponding circle name or owner correlation found; left unassigned pending explicit reconciliation."
    },
    {
      "ID": "G-036",
      "Name": "Tech",
      "Type": "Circle",
      "Parent Circle ID": "G-001",
      "Purpose": "",
      "Accountabilities": "",
      "Scope": "",
      "Privileges": "",
      "Status": "Retired",
      "Lead Link": "Unassigned",
      "Person ID": "",
      "Definition note": "Added 2026-09-22 as a new top-level circle; takes over Knowledge Base Circle (G-015) from Empowerment. Purpose/Accountabilities/Scope not yet documented. Retired 2026-09-23: after Knowledge Base consolidation, its only child was G-030. The continuing role now sits in Sapiens First Global."
    },
    {
      "ID": "G-037",
      "Name": "Background Researcher",
      "Type": "Role",
      "Parent Circle ID": "G-007",
      "Purpose": "",
      "Accountabilities": "",
      "Scope": "",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Unassigned",
      "Person ID": "",
      "Definition note": "Added 2026-09-22 under Advocacy Circle. Purpose/Accountabilities not yet documented."
    },
    {
      "ID": "G-038",
      "Name": "Policy Ask Creator",
      "Type": "Role",
      "Parent Circle ID": "G-007",
      "Purpose": "",
      "Accountabilities": "",
      "Scope": "",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Unassigned",
      "Person ID": "",
      "Definition note": "Added 2026-09-22 under Advocacy Circle. Purpose/Accountabilities not yet documented."
    },
    {
      "ID": "G-039",
      "Name": "No Killer Robots Owner",
      "Type": "Role",
      "Parent Circle ID": "G-007",
      "Purpose": "",
      "Accountabilities": "",
      "Scope": "",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Unassigned",
      "Person ID": "",
      "Definition note": "Added 2026-09-22 under Advocacy Circle. Purpose/Accountabilities not yet documented."
    },
    {
      "ID": "G-040",
      "Name": "Campaign Strategist",
      "Type": "Role",
      "Parent Circle ID": "G-007",
      "Purpose": "",
      "Accountabilities": "",
      "Scope": "",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Unassigned",
      "Person ID": "",
      "Definition note": "Added 2026-09-22 under Advocacy Circle. Purpose/Accountabilities not yet documented."
    },
    {
      "ID": "G-041",
      "Name": "Meta",
      "Type": "Circle",
      "Parent Circle ID": "G-001",
      "Purpose": "Movement has a vision, strategy, and financial support.",
      "Accountabilities": "",
      "Scope": "",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "",
      "Person ID": "",
      "Definition note": "Created 2026-09-23 to contain Vision & Strategy and Finance & Fundraising; assignment not yet recorded."
    }
  ],
  "relationships": [
    {
      "ID": "R-001",
      "From ID": "G-002",
      "Relationship": "owns",
      "To ID": "D-001",
      "Valid from": "",
      "Valid until": "",
      "Notes": "Imported ownership; start date not recorded."
    },
    {
      "ID": "R-002",
      "From ID": "G-021",
      "Relationship": "owns",
      "To ID": "D-002",
      "Valid from": "",
      "Valid until": "",
      "Notes": "Imported ownership; start date not recorded."
    },
    {
      "ID": "R-003",
      "From ID": "G-022",
      "Relationship": "owns",
      "To ID": "D-003",
      "Valid from": "",
      "Valid until": "",
      "Notes": "Imported ownership; start date not recorded."
    },
    {
      "ID": "R-004",
      "From ID": "G-023",
      "Relationship": "owns",
      "To ID": "D-004",
      "Valid from": "",
      "Valid until": "",
      "Notes": "Imported ownership; start date not recorded."
    },
    {
      "ID": "R-005",
      "From ID": "G-024",
      "Relationship": "owns",
      "To ID": "D-005",
      "Valid from": "",
      "Valid until": "",
      "Notes": "Imported ownership; start date not recorded."
    },
    {
      "ID": "R-006",
      "From ID": "G-025",
      "Relationship": "owns",
      "To ID": "D-006",
      "Valid from": "",
      "Valid until": "",
      "Notes": "Imported ownership; start date not recorded."
    },
    {
      "ID": "R-007",
      "From ID": "G-026",
      "Relationship": "owns",
      "To ID": "D-007",
      "Valid from": "",
      "Valid until": "",
      "Notes": "Imported ownership; start date not recorded."
    },
    {
      "ID": "R-008",
      "From ID": "G-023",
      "Relationship": "owns",
      "To ID": "D-008",
      "Valid from": "",
      "Valid until": "",
      "Notes": "Imported ownership; start date not recorded."
    },
    {
      "ID": "R-009",
      "From ID": "G-027",
      "Relationship": "owns",
      "To ID": "D-009",
      "Valid from": "",
      "Valid until": "",
      "Notes": "Imported ownership; start date not recorded."
    },
    {
      "ID": "R-010",
      "From ID": "G-028",
      "Relationship": "owns",
      "To ID": "D-010",
      "Valid from": "",
      "Valid until": "",
      "Notes": "Imported ownership; start date not recorded."
    },
    {
      "ID": "R-011",
      "From ID": "G-029",
      "Relationship": "owns",
      "To ID": "D-011",
      "Valid from": "",
      "Valid until": "",
      "Notes": "Imported ownership; start date not recorded."
    },
    {
      "ID": "R-012",
      "From ID": "G-005",
      "Relationship": "owns",
      "To ID": "D-012",
      "Valid from": "",
      "Valid until": "",
      "Notes": "Imported ownership; start date not recorded."
    },
    {
      "ID": "R-013",
      "From ID": "G-006",
      "Relationship": "owns",
      "To ID": "D-013",
      "Valid from": "",
      "Valid until": "",
      "Notes": "Imported ownership; start date not recorded."
    },
    {
      "ID": "R-014",
      "From ID": "G-030",
      "Relationship": "owns",
      "To ID": "D-014",
      "Valid from": "",
      "Valid until": "",
      "Notes": "Imported ownership; start date not recorded."
    },
    {
      "ID": "R-015",
      "From ID": "G-031",
      "Relationship": "owns",
      "To ID": "D-015",
      "Valid from": "",
      "Valid until": "",
      "Notes": "Imported ownership; start date not recorded."
    },
    {
      "ID": "R-016",
      "From ID": "G-032",
      "Relationship": "owns",
      "To ID": "D-016",
      "Valid from": "",
      "Valid until": "",
      "Notes": "Imported ownership; start date not recorded."
    },
    {
      "ID": "R-017",
      "From ID": "G-033",
      "Relationship": "owns",
      "To ID": "D-017",
      "Valid from": "",
      "Valid until": "",
      "Notes": "Imported ownership; start date not recorded."
    },
    {
      "ID": "R-018",
      "From ID": "G-034",
      "Relationship": "owns",
      "To ID": "D-018",
      "Valid from": "",
      "Valid until": "",
      "Notes": "Imported ownership; start date not recorded."
    },
    {
      "ID": "R-019",
      "From ID": "G-025",
      "Relationship": "owns",
      "To ID": "D-019",
      "Valid from": "",
      "Valid until": "",
      "Notes": "Imported ownership; start date not recorded."
    },
    {
      "ID": "R-020",
      "From ID": "G-035",
      "Relationship": "owns",
      "To ID": "D-020",
      "Valid from": "",
      "Valid until": "",
      "Notes": "Imported ownership; start date not recorded."
    },
    {
      "ID": "R-021",
      "From ID": "G-037",
      "Relationship": "owns",
      "To ID": "D-024",
      "Valid from": "",
      "Valid until": "",
      "Notes": "Added 2026-09-22 per governance restructuring."
    },
    {
      "ID": "R-022",
      "From ID": "G-037",
      "Relationship": "owns",
      "To ID": "D-025",
      "Valid from": "",
      "Valid until": "",
      "Notes": "Added 2026-09-22 per governance restructuring."
    },
    {
      "ID": "R-023",
      "From ID": "G-038",
      "Relationship": "owns",
      "To ID": "D-026",
      "Valid from": "",
      "Valid until": "",
      "Notes": "Added 2026-09-22 per governance restructuring."
    },
    {
      "ID": "R-024",
      "From ID": "G-038",
      "Relationship": "owns",
      "To ID": "D-027",
      "Valid from": "",
      "Valid until": "",
      "Notes": "Added 2026-09-22 per governance restructuring."
    },
    {
      "ID": "R-025",
      "From ID": "G-039",
      "Relationship": "owns",
      "To ID": "D-028",
      "Valid from": "",
      "Valid until": "",
      "Notes": "Added 2026-09-22 per governance restructuring."
    },
    {
      "ID": "R-026",
      "From ID": "G-040",
      "Relationship": "owns",
      "To ID": "D-029",
      "Valid from": "",
      "Valid until": "",
      "Notes": "Added 2026-09-22 per governance restructuring."
    },
    {
      "ID": "R-027",
      "From ID": "G-002",
      "Relationship": "succeeds",
      "To ID": "G-003",
      "Valid from": "2026-09-23",
      "Valid until": "",
      "Notes": "Single-role circle consolidated into its continuing role by user direction; existing role ownership retained."
    },
    {
      "ID": "R-028",
      "From ID": "G-033",
      "Relationship": "succeeds",
      "To ID": "G-012",
      "Valid from": "2026-09-23",
      "Valid until": "",
      "Notes": "Single-role circle consolidated into its continuing role by user direction; existing role ownership retained."
    },
    {
      "ID": "R-029",
      "From ID": "G-026",
      "Relationship": "succeeds",
      "To ID": "G-014",
      "Valid from": "2026-09-23",
      "Valid until": "",
      "Notes": "Single-role circle consolidated into its continuing role by user direction; existing role ownership retained."
    },
    {
      "ID": "R-030",
      "From ID": "G-030",
      "Relationship": "succeeds",
      "To ID": "G-015",
      "Valid from": "2026-09-23",
      "Valid until": "",
      "Notes": "Single-role circle consolidated into its continuing role by user direction; existing role ownership retained."
    },
    {
      "ID": "R-031",
      "From ID": "G-031",
      "Relationship": "succeeds",
      "To ID": "G-018",
      "Valid from": "2026-09-23",
      "Valid until": "",
      "Notes": "Single-role circle consolidated into its continuing role by user direction; existing role ownership retained."
    },
    {
      "ID": "R-032",
      "From ID": "G-030",
      "Relationship": "succeeds",
      "To ID": "G-036",
      "Valid from": "2026-09-23",
      "Valid until": "",
      "Notes": "Tech contained only the continuing Knowledge Base role after consolidation; apply the single-role-circle rule recursively."
    }
  ]
};
