// Generated from data/atlas/*.csv by build.py. Edit the CSVs, not this file.
window.ATLAS_DATA = {
  "domains": [
    {
      "ID": "D-001",
      "Name": "Current Mission",
      "Type": "Mission",
      "Program category": "",
      "Purpose": "Revolutionary social and political change around AI governance.",
      "Parent ID": "",
      "Circle ID": "G-001",
      "Status": "Planned",
      "Stage": "Ideated",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": ""
    },
    {
      "ID": "D-002",
      "Name": "Advocacy",
      "Type": "Pillar",
      "Program category": "",
      "Purpose": "Pillars of support—civil society institutions, politicians, and media—become supporters.",
      "Parent ID": "D-001",
      "Circle ID": "",
      "Status": "Active",
      "Stage": "In Progress",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "Converts public pressure into binding policy",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": ""
    },
    {
      "ID": "D-003",
      "Name": "Community",
      "Type": "Pillar",
      "Program category": "",
      "Purpose": "Large numbers of people participate as active supporters.",
      "Parent ID": "D-001",
      "Circle ID": "",
      "Status": "Planned",
      "Stage": "Approved",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "Scales the movement beyond the founding team",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": ""
    },
    {
      "ID": "D-004",
      "Name": "Empowerment",
      "Type": "Pillar",
      "Program category": "",
      "Purpose": "Abundant leadership within the movement.",
      "Parent ID": "D-001",
      "Circle ID": "",
      "Status": "Active",
      "Stage": "In Progress",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "Builds the volunteer capacity everything else depends on",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": ""
    },
    {
      "ID": "D-005",
      "Name": "Stop 1984",
      "Type": "Product/Service",
      "Program category": "",
      "Purpose": "End AI-enabled mass surveillance.",
      "Parent ID": "D-033",
      "Circle ID": "",
      "Status": "Active",
      "Stage": "In Progress",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "First proof point: local win building toward statewide policy",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": ""
    },
    {
      "ID": "D-006",
      "Name": "Chapters",
      "Type": "Program",
      "Program category": "",
      "Purpose": "Passive supporters become Members by connecting locally.",
      "Parent ID": "D-003",
      "Circle ID": "",
      "Status": "Planned",
      "Stage": "Proposed",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "Distributed growth engine",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": ""
    },
    {
      "ID": "D-007",
      "Name": "Global Fellowship",
      "Type": "Product/Service",
      "Program category": "",
      "Purpose": "Members, regardless of location, can contribute meaningfully to movement infrastructure.",
      "Parent ID": "D-038",
      "Circle ID": "",
      "Status": "Active",
      "Stage": "In Progress",
      "Started on": "",
      "Ended on": "",
      "Key Features": "Semester cohorts, 1 project/Fellow, kickoff + coworking sessions, 3 exit paths",
      "User": "Volunteers seeking high-ownership involvement",
      "Value Proposition": "Turns motivated volunteers into skilled, accountable contributors in one semester",
      "SOP URL": "",
      "SOP Notes": "Exists — Fellowship Handbook",
      "Ownership note": ""
    },
    {
      "ID": "D-008",
      "Name": "Training",
      "Type": "Product/Service",
      "Program category": "",
      "Purpose": "Knowledge spreads throughout Members and Fellows.",
      "Parent ID": "D-037",
      "Circle ID": "",
      "Status": "Planned",
      "Stage": "Ideated",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "Two-Year Roadmap commitment; not yet started",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": ""
    },
    {
      "ID": "D-009",
      "Name": "Communications",
      "Type": "Program",
      "Program category": "",
      "Purpose": "People understand the movement and stay engaged.",
      "Parent ID": "D-003",
      "Circle ID": "",
      "Status": "Active",
      "Stage": "In Progress",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "Serves all three pillars, not one campaign",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": ""
    },
    {
      "ID": "D-010",
      "Name": "Finance & Fundraising",
      "Type": "Program",
      "Program category": "",
      "Purpose": "Movement has the money to execute its strategy.",
      "Parent ID": "D-031",
      "Circle ID": "",
      "Status": "Active",
      "Stage": "In Progress",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "Funds runway for everything above",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": ""
    },
    {
      "ID": "D-011",
      "Name": "Operations & Infrastructure",
      "Type": "Program",
      "Program category": "Enabling",
      "Purpose": "Systems that let a lean team run at scale",
      "Parent ID": "D-001",
      "Circle ID": "",
      "Status": "Active",
      "Stage": "In Progress",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "Removes the founder as a bottleneck",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": ""
    },
    {
      "ID": "D-012",
      "Name": "Media Program",
      "Type": "Product/Service",
      "Program category": "",
      "Purpose": "Ongoing press/spokesperson capability usable by any campaign",
      "Parent ID": "D-009",
      "Circle ID": "G-004",
      "Status": "Planned",
      "Stage": "Proposed",
      "Started on": "",
      "Ended on": "",
      "Key Features": "Media moments, journalist relationships, press kit, spokesperson training, visual identity bank",
      "User": "Press, public, prospective members",
      "Value Proposition": "Converts campaign wins into public visibility that accelerates recruitment",
      "SOP URL": "",
      "SOP Notes": "Missing",
      "Ownership note": ""
    },
    {
      "ID": "D-013",
      "Name": "Website",
      "Type": "Product/Service",
      "Program category": "",
      "Purpose": "Visitors understand the movement and know how to participate.",
      "Parent ID": "D-009",
      "Circle ID": "G-004",
      "Status": "Active",
      "Stage": "In Progress",
      "Started on": "",
      "Ended on": "",
      "Key Features": "Campaign pages, strategy page, donate page",
      "User": "All external visitors",
      "Value Proposition": "Primary conversion and credibility surface",
      "SOP URL": "",
      "SOP Notes": "Missing",
      "Ownership note": ""
    },
    {
      "ID": "D-014",
      "Name": "Resource Center",
      "Type": "Product/Service",
      "Program category": "",
      "Purpose": "Social movement resources and know-how are clear and accessible.",
      "Parent ID": "D-037",
      "Circle ID": "",
      "Status": "Active",
      "Stage": "In Progress",
      "Started on": "",
      "Ended on": "",
      "Key Features": "Wiki.js base, information architecture, contribution/permission rules",
      "User": "All Fellows, organizers, chapter leaders",
      "Value Proposition": "Lets the org scale past founder-memory",
      "SOP URL": "",
      "SOP Notes": "In progress — this IS the SOP system",
      "Ownership note": ""
    },
    {
      "ID": "D-015",
      "Name": "Membership Registration & Onboarding",
      "Type": "Product/Service",
      "Program category": "",
      "Purpose": "Supporters can easily join and start participating.",
      "Parent ID": "D-036",
      "Circle ID": "",
      "Status": "Active",
      "Stage": "In Progress",
      "Started on": "",
      "Ended on": "",
      "Key Features": "Stripe + CRM + Discord integration, onboarding/offboarding automation",
      "User": "Dues-paying members (M2+)",
      "Value Proposition": "Reliable, low-labor pipeline from interested to active member",
      "SOP URL": "",
      "SOP Notes": "Missing",
      "Ownership note": ""
    },
    {
      "ID": "D-016",
      "Name": "House Party Fundraising Kit",
      "Type": "Product/Service",
      "Program category": "",
      "Purpose": "Turnkey fundraiser-hosting kit",
      "Parent ID": "D-010",
      "Circle ID": "",
      "Status": "Planned",
      "Stage": "Proposed",
      "Started on": "",
      "Ended on": "",
      "Key Features": "Invitation templates, host guide, ask script, donation page, automated follow-up",
      "User": "Supporter-hosts running small fundraisers",
      "Value Proposition": "Multiplies fundraising capacity without staff presence",
      "SOP URL": "",
      "SOP Notes": "Missing",
      "Ownership note": ""
    },
    {
      "ID": "D-017",
      "Name": "Social Media",
      "Type": "Product/Service",
      "Program category": "",
      "Purpose": "People encounter, follow, and share the movement.",
      "Parent ID": "D-009",
      "Circle ID": "",
      "Status": "Planned",
      "Stage": "Proposed",
      "Started on": "",
      "Ended on": "",
      "Key Features": "Repeatable content workflow, scheduling automation, measurement",
      "User": "Broader public, prospective supporters",
      "Value Proposition": "Compounding reach at low marginal cost",
      "SOP URL": "",
      "SOP Notes": "Missing",
      "Ownership note": ""
    },
    {
      "ID": "D-018",
      "Name": "Newspaper",
      "Type": "Product/Service",
      "Program category": "",
      "Purpose": "Members stay informed, connected, and engaged.",
      "Parent ID": "D-036",
      "Circle ID": "",
      "Status": "Active",
      "Stage": "In Progress",
      "Started on": "",
      "Ended on": "",
      "Key Features": "Recurring sections, submission process, editorial workflow",
      "User": "Members & movement readers",
      "Value Proposition": "Builds durable voice; low-barrier way for Fellows to contribute writing",
      "SOP URL": "",
      "SOP Notes": "Missing — Jan launch target",
      "Ownership note": ""
    },
    {
      "ID": "D-019",
      "Name": "Start a Circle",
      "Type": "Product/Service",
      "Program category": "",
      "Purpose": "Members can easily start local groups.",
      "Parent ID": "D-006",
      "Circle ID": "",
      "Status": "Planned",
      "Stage": "Proposed",
      "Started on": "",
      "Ended on": "",
      "Key Features": "Constitution, lifecycle model, Discord architecture, leader onboarding",
      "User": "Local organizers starting a chapter",
      "Value Proposition": "Lets the movement scale to hundreds of chapters without a central bottleneck",
      "SOP URL": "",
      "SOP Notes": "Missing",
      "Ownership note": ""
    },
    {
      "ID": "D-020",
      "Name": "General Meetings",
      "Type": "Product/Service",
      "Program category": "",
      "Purpose": "Recurring member-facing convening (not a Holacracy governance meeting)",
      "Parent ID": "D-001",
      "Circle ID": "",
      "Status": "Active",
      "Stage": "In Progress",
      "Started on": "",
      "Ended on": "",
      "Key Features": "Recurring cadence, prepped content/questions, breakout rooms, Discord announcement",
      "User": "Members & supporters, all engagement levels",
      "Value Proposition": "Regular touchpoint that builds belonging and surfaces org news",
      "SOP URL": "",
      "SOP Notes": "Partial — steps exist in Active Projects, not written up",
      "Ownership note": ""
    },
    {
      "ID": "D-021",
      "Name": "1-1s",
      "Type": "Product/Service",
      "Program category": "",
      "Purpose": "Relational check-ins outside formal governance process",
      "Parent ID": "D-001",
      "Circle ID": "",
      "Status": "Active",
      "Stage": "In Progress",
      "Started on": "",
      "Ended on": "",
      "Key Features": "Regular founder/lead check-ins, onboarding, mentorship",
      "User": "Fellows, new members, prospective leaders/donors",
      "Value Proposition": "High-touch trust-building that async channels can't replicate",
      "SOP URL": "",
      "SOP Notes": "Missing",
      "Ownership note": "Responsibility assigned to Fellowship Coordinator under the user-directed default."
    },
    {
      "ID": "D-022",
      "Name": "Freeze AI Campaign",
      "Type": "Product/Service",
      "Program category": "",
      "Purpose": "",
      "Parent ID": "D-033",
      "Circle ID": "",
      "Status": "Needs definition",
      "Stage": "",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": "Added 2026-09-22 per governance restructuring; Purpose/Stage not yet specified."
    },
    {
      "ID": "D-023",
      "Name": "No Killer Robots",
      "Type": "Product/Service",
      "Program category": "",
      "Purpose": "Regulate deadly autonomous weapons.",
      "Parent ID": "D-033",
      "Circle ID": "",
      "Status": "Needs definition",
      "Stage": "",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": "Added 2026-09-22 per governance restructuring; Purpose/Stage not yet specified."
    },
    {
      "ID": "D-024",
      "Name": "Stop 1984! Background Research",
      "Type": "Project",
      "Program category": "",
      "Purpose": "",
      "Parent ID": "D-005",
      "Circle ID": "",
      "Status": "Needs definition",
      "Stage": "",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": "Added 2026-09-22 per governance restructuring; owned by Background Researcher (G-037)."
    },
    {
      "ID": "D-025",
      "Name": "Freeze AI Background Research",
      "Type": "Project",
      "Program category": "",
      "Purpose": "",
      "Parent ID": "D-022",
      "Circle ID": "",
      "Status": "Needs definition",
      "Stage": "",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": "Added 2026-09-22 per governance restructuring; owned by Background Researcher (G-037)."
    },
    {
      "ID": "D-026",
      "Name": "Stop 1984! Asks",
      "Type": "Project",
      "Program category": "",
      "Purpose": "",
      "Parent ID": "D-005",
      "Circle ID": "",
      "Status": "Needs definition",
      "Stage": "",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": "Added 2026-09-22 per governance restructuring; owned by Policy Ask Creator (G-038)."
    },
    {
      "ID": "D-027",
      "Name": "Freeze AI Asks",
      "Type": "Project",
      "Program category": "",
      "Purpose": "",
      "Parent ID": "D-022",
      "Circle ID": "",
      "Status": "Needs definition",
      "Stage": "",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": "Added 2026-09-22 per governance restructuring; owned by Policy Ask Creator (G-038)."
    },
    {
      "ID": "D-028",
      "Name": "No Killer Robots Policy",
      "Type": "Project",
      "Program category": "",
      "Purpose": "",
      "Parent ID": "D-023",
      "Circle ID": "",
      "Status": "Needs definition",
      "Stage": "",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": "Added 2026-09-22 per governance restructuring; owned by No Killer Robots Owner (G-039)."
    },
    {
      "ID": "D-029",
      "Name": "Stop 1984 CA Strategic Plan",
      "Type": "Project",
      "Program category": "",
      "Purpose": "A clear California campaign strategy sequences winnable action.",
      "Parent ID": "D-005",
      "Circle ID": "",
      "Status": "Needs definition",
      "Stage": "",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": "Added 2026-09-22 per governance restructuring; owned by Campaign Strategist (G-040)."
    },
    {
      "ID": "D-030",
      "Name": "Stop 1984! Campaign Design",
      "Type": "Project",
      "Program category": "",
      "Purpose": "Campaign organizers have reusable Stop 1984 media resources.",
      "Parent ID": "D-005",
      "Circle ID": "G-004",
      "Status": "Needs definition",
      "Stage": "",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": "Added 2026-09-22 per governance restructuring; held undelegated by Media Circle (G-004), no specific role named."
    },
    {
      "ID": "D-031",
      "Name": "DNA",
      "Type": "Pillar",
      "Program category": "",
      "Purpose": "Movement has a vision, strategy, and financial support.",
      "Parent ID": "D-001",
      "Circle ID": "",
      "Status": "Needs definition",
      "Stage": "",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": ""
    },
    {
      "ID": "D-032",
      "Name": "Vision & Strategy",
      "Type": "Program",
      "Program category": "",
      "Purpose": "Movement has a clear vision and strategy.",
      "Parent ID": "D-031",
      "Circle ID": "",
      "Status": "Needs definition",
      "Stage": "",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": ""
    },
    {
      "ID": "D-033",
      "Name": "Campaign Creation",
      "Type": "Program",
      "Program category": "",
      "Purpose": "Build priority campaigns.",
      "Parent ID": "D-002",
      "Circle ID": "",
      "Status": "Needs definition",
      "Stage": "",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": ""
    },
    {
      "ID": "D-034",
      "Name": "Campaign Support",
      "Type": "Program",
      "Program category": "",
      "Purpose": "Campaigns have what they need to succeed.",
      "Parent ID": "D-002",
      "Circle ID": "",
      "Status": "Needs definition",
      "Stage": "",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": ""
    },
    {
      "ID": "D-035",
      "Name": "Campaign Execution Toolkit",
      "Type": "Product/Service",
      "Program category": "",
      "Purpose": "Organizers have the tools to run effective campaigns.",
      "Parent ID": "D-034",
      "Circle ID": "",
      "Status": "Needs definition",
      "Stage": "",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": ""
    },
    {
      "ID": "D-036",
      "Name": "Global Membership",
      "Type": "Program",
      "Program category": "",
      "Purpose": "Passive supporters anywhere have a way to deepen their commitment.",
      "Parent ID": "D-003",
      "Circle ID": "",
      "Status": "Needs definition",
      "Stage": "",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": ""
    },
    {
      "ID": "D-037",
      "Name": "Knowledge",
      "Type": "Program",
      "Program category": "",
      "Purpose": "Members know why and how to participate.",
      "Parent ID": "D-004",
      "Circle ID": "",
      "Status": "Needs definition",
      "Stage": "",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": ""
    },
    {
      "ID": "D-038",
      "Name": "Development",
      "Type": "Program",
      "Program category": "",
      "Purpose": "Members are empowered to take over projects and domains.",
      "Parent ID": "D-004",
      "Circle ID": "",
      "Status": "Needs definition",
      "Stage": "",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": ""
    },
    {
      "ID": "D-039",
      "Name": "Governance",
      "Type": "Program",
      "Program category": "",
      "Purpose": "Clear structure and roles for all Fellows & Staff.",
      "Parent ID": "D-004",
      "Circle ID": "",
      "Status": "Needs definition",
      "Stage": "",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": ""
    },
    {
      "ID": "D-040",
      "Name": "Role Management",
      "Type": "Product/Service",
      "Program category": "",
      "Purpose": "Fellows hold domains that suit their strengths.",
      "Parent ID": "D-039",
      "Circle ID": "",
      "Status": "Needs definition",
      "Stage": "",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": ""
    },
    {
      "ID": "D-041",
      "Name": "Project Management",
      "Type": "Product/Service",
      "Program category": "",
      "Purpose": "Teams break down and strategically prioritize projects within each domain.",
      "Parent ID": "D-039",
      "Circle ID": "",
      "Status": "Needs definition",
      "Stage": "",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": ""
    },
    {
      "ID": "D-042",
      "Name": "Knowledge Management System",
      "Type": "Product/Service",
      "Program category": "",
      "Purpose": "Reliable infrastructure makes movement knowledge accessible and maintainable.",
      "Parent ID": "D-011",
      "Circle ID": "G-036",
      "Status": "Active",
      "Stage": "",
      "Started on": "",
      "Ended on": "",
      "Key Features": "",
      "User": "",
      "Value Proposition": "",
      "SOP URL": "",
      "SOP Notes": "",
      "Ownership note": ""
    }
  ],
  "governance": [
    {
      "ID": "G-001",
      "Name": "Sapiens First Global",
      "Type": "Circle",
      "Parent Circle ID": "",
      "Purpose": "Revolutionary social and political change around AI governance.",
      "Accountabilities": "Maintaining movement-wide direction; coordinating shared resources and organizational records; supporting the work of its circles",
      "Scope": "",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Rohan",
      "Person ID": "P-001",
      "Definition note": "",
      "Engagement level": "Staff",
      "Assignment basis": "User-directed default assignment"
    },
    {
      "ID": "G-002",
      "Name": "Vision & Strategy",
      "Type": "Role",
      "Parent Circle ID": "G-041",
      "Purpose": "Cross-pillar strategic planning; Keep the org anchored to Purpose over time",
      "Accountabilities": "Setting/tracking OKRs; surfacing what's slipping; sequencing priority-city rankings; Reviewing major strategic decisions against Purpose; resolving Purpose-level tensions",
      "Scope": "Org-wide OKRs, quarterly priorities; Final call on Purpose/Vision statements",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Rohan",
      "Person ID": "P-001",
      "Definition note": "Parent circle changed from General Company Circle (G-001) to Vision & Strategy Circle (G-003) per 2026-09-22 governance restructuring. Merged with G-003 on 2026-09-23; continuing role retains its ID and work ownership. Purpose, accountabilities, scope, privileges, and recorded assignment carried forward from the wrapper.",
      "Engagement level": "Staff",
      "Assignment basis": "User-directed default assignment"
    },
    {
      "ID": "G-003",
      "Name": "Vision & Strategy",
      "Type": "Circle",
      "Parent Circle ID": "G-001",
      "Purpose": "Cross-pillar strategic planning",
      "Accountabilities": "Setting/tracking OKRs; surfacing what's slipping; sequencing priority-city rankings",
      "Scope": "Org-wide OKRs, quarterly priorities",
      "Privileges": "",
      "Status": "Retired",
      "Lead Link": "Rohan",
      "Person ID": "",
      "Definition note": "Renamed from Strategy Circle on 2026-09-22. Retired 2026-09-23: single-role circle consolidated into G-002; see the dated succeeds relationship.",
      "Engagement level": "",
      "Assignment basis": ""
    },
    {
      "ID": "G-004",
      "Name": "Media",
      "Type": "Circle",
      "Parent Circle ID": "G-001",
      "Purpose": "Own how Sapiens First is seen and heard externally",
      "Accountabilities": "Maintaining visual identity; approving public statements; managing press",
      "Scope": "Brand, external messaging, website content",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Rohan",
      "Person ID": "P-001",
      "Definition note": "Renamed from Communications & Narrative Circle on 2026-09-22.",
      "Engagement level": "Staff",
      "Assignment basis": "User-directed default assignment"
    },
    {
      "ID": "G-005",
      "Name": "Spokesperson",
      "Type": "Role",
      "Parent Circle ID": "G-004",
      "Purpose": "Represent Sapiens First publicly with a consistent voice",
      "Accountabilities": "Media training; interview prep; approving quotes attributed to the org",
      "Scope": "Public statements, media interviews",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Rohan",
      "Person ID": "P-001",
      "Definition note": "",
      "Engagement level": "Staff",
      "Assignment basis": "User-directed default assignment"
    },
    {
      "ID": "G-006",
      "Name": "Website Owner",
      "Type": "Role",
      "Parent Circle ID": "G-004",
      "Purpose": "Keep sapiensfirst.org accurate and converting",
      "Accountabilities": "Publishing updates; maintaining donate/strategy/campaign pages",
      "Scope": "Site content, structure, hosting",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Rohan",
      "Person ID": "P-001",
      "Definition note": "",
      "Engagement level": "Staff",
      "Assignment basis": "User-directed default assignment"
    },
    {
      "ID": "G-007",
      "Name": "Advocacy",
      "Type": "Circle",
      "Parent Circle ID": "G-001",
      "Purpose": "Win policy that restricts AI-enabled harm",
      "Accountabilities": "Choosing campaigns; setting policy platform; coalition strategy",
      "Scope": "Campaign selection, policy asks",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Rohan",
      "Person ID": "P-001",
      "Definition note": "",
      "Engagement level": "Staff",
      "Assignment basis": "User-directed default assignment"
    },
    {
      "ID": "G-008",
      "Name": "Stop 1984!",
      "Type": "Circle",
      "Parent Circle ID": "G-007",
      "Purpose": "Ban AI-enabled mass surveillance, starting in California",
      "Accountabilities": "Research library; policy platform; city-by-city strategic plan; media resources",
      "Scope": "Campaign research, asks, media, strategic plan",
      "Privileges": "",
      "Status": "Retired",
      "Lead Link": "Al",
      "Person ID": "",
      "Definition note": " Retired 2026-09-23: Campaign coordination is carried directly by roles in Advocacy.",
      "Engagement level": "",
      "Assignment basis": ""
    },
    {
      "ID": "G-009",
      "Name": "Stop 1984 CA Strategist",
      "Type": "Role",
      "Parent Circle ID": "G-007",
      "Purpose": "A focused California strategy advances the campaign to end AI-enabled mass surveillance.",
      "Accountabilities": "Mapping decision-makers and coalition opportunities; prioritizing California cities and campaign milestones; maintaining the campaign strategic plan; coordinating research, policy asks, and organizing work",
      "Scope": "California campaign strategy and city playbooks",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Al",
      "Person ID": "P-004",
      "Definition note": " Updated from user-directed governance and role definitions on 2026-09-23.",
      "Engagement level": "Fellow",
      "Assignment basis": "User-provided project match"
    },
    {
      "ID": "G-010",
      "Name": "Community",
      "Type": "Circle",
      "Parent Circle ID": "G-001",
      "Purpose": "Build a nationwide network of local chapters",
      "Accountabilities": "Chapter lifecycle; member onboarding/offboarding; digital presence",
      "Scope": "Chapter model, member engagement, social content",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Rohan",
      "Person ID": "P-001",
      "Definition note": "",
      "Engagement level": "Staff",
      "Assignment basis": "User-directed default assignment"
    },
    {
      "ID": "G-011",
      "Name": "Chapter Network",
      "Type": "Circle",
      "Parent Circle ID": "G-010",
      "Purpose": "Make starting/running a chapter easy and safe",
      "Accountabilities": "Starter kit; leader vetting; dispute handling; chapter lifecycle management",
      "Scope": "Chapter constitution, Discord architecture",
      "Privileges": "",
      "Status": "Retired",
      "Lead Link": "Unassigned",
      "Person ID": "",
      "Definition note": " Retired 2026-09-23: Chapter Network removed; Berkeley Chapter is a separate root circle, not its organizational successor.",
      "Engagement level": "",
      "Assignment basis": ""
    },
    {
      "ID": "G-012",
      "Name": "Digital Presence",
      "Type": "Circle",
      "Parent Circle ID": "G-010",
      "Purpose": "Grow reach across social channels",
      "Accountabilities": "Content production workflow; approval process; channel metrics",
      "Scope": "Content calendar, scheduling automations",
      "Privileges": "",
      "Status": "Retired",
      "Lead Link": "Unassigned",
      "Person ID": "",
      "Definition note": " Retired 2026-09-23: single-role circle consolidated into G-033; see the dated succeeds relationship.",
      "Engagement level": "",
      "Assignment basis": ""
    },
    {
      "ID": "G-013",
      "Name": "Empowerment",
      "Type": "Circle",
      "Parent Circle ID": "G-001",
      "Purpose": "Train and onboard leaders/activists at scale",
      "Accountabilities": "Cohort management; curriculum; leadership academy",
      "Scope": "Fellowship program, leadership curriculum",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Rohan",
      "Person ID": "P-001",
      "Definition note": "",
      "Engagement level": "Staff",
      "Assignment basis": "User-directed default assignment"
    },
    {
      "ID": "G-014",
      "Name": "Fellowship Program",
      "Type": "Circle",
      "Parent Circle ID": "G-013",
      "Purpose": "Run the Fellowship end-to-end",
      "Accountabilities": "Applicant funnel; project matching; check-ins; offboarding",
      "Scope": "Recruitment, matching, cohort management",
      "Privileges": "",
      "Status": "Retired",
      "Lead Link": "Unassigned",
      "Person ID": "",
      "Definition note": " Retired 2026-09-23: single-role circle consolidated into G-026; see the dated succeeds relationship.",
      "Engagement level": "",
      "Assignment basis": ""
    },
    {
      "ID": "G-015",
      "Name": "Knowledge Base",
      "Type": "Circle",
      "Parent Circle ID": "G-036",
      "Purpose": "Centralize organizational knowledge",
      "Accountabilities": "Content ownership rules; permissions; keeping content current",
      "Scope": "Wiki.js, information architecture",
      "Privileges": "",
      "Status": "Retired",
      "Lead Link": "Da",
      "Person ID": "",
      "Definition note": "Parent circle changed from Empowerment Circle (G-013) to Tech Circle (G-036) per 2026-09-22 governance restructuring: Tech owns knowledge management. Retired 2026-09-23: single-role circle consolidated into G-030; see the dated succeeds relationship.",
      "Engagement level": "",
      "Assignment basis": ""
    },
    {
      "ID": "G-016",
      "Name": "Newspaper",
      "Type": "Circle",
      "Parent Circle ID": "G-013",
      "Purpose": "Publish the Sapiens First Newspaper",
      "Accountabilities": "Submissions process; editorial standards; production cadence",
      "Scope": "Editorial voice, sections, production",
      "Privileges": "",
      "Status": "Retired",
      "Lead Link": "Vi",
      "Person ID": "",
      "Definition note": " Retired 2026-09-23: Newspaper is energized by Newspaper Editor-in-Chief (G-034) within Community.",
      "Engagement level": "",
      "Assignment basis": ""
    },
    {
      "ID": "G-017",
      "Name": "Biz Ops",
      "Type": "Circle",
      "Parent Circle ID": "G-001",
      "Purpose": "Systems that let a lean team run at scale",
      "Accountabilities": "Campaign automations; data integrity; 501(c)(3)/(c)(4) compliance; budget tracking",
      "Scope": "CRM, automations, legal/compliance, finance",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Rohan",
      "Person ID": "P-001",
      "Definition note": "Renamed from Operations & Infrastructure Circle on 2026-09-22.",
      "Engagement level": "Staff",
      "Assignment basis": "User-directed default assignment"
    },
    {
      "ID": "G-018",
      "Name": "Membership Systems",
      "Type": "Circle",
      "Parent Circle ID": "G-017",
      "Purpose": "Automate the member lifecycle",
      "Accountabilities": "Onboarding/offboarding triggers; failure handling; privacy/backups",
      "Scope": "Stripe, CRM, Discord integration",
      "Privileges": "",
      "Status": "Retired",
      "Lead Link": "Ba",
      "Person ID": "",
      "Definition note": " Retired 2026-09-23: single-role circle consolidated into G-031; see the dated succeeds relationship.",
      "Engagement level": "",
      "Assignment basis": ""
    },
    {
      "ID": "G-019",
      "Name": "Finance & Fundraising",
      "Type": "Circle",
      "Parent Circle ID": "G-041",
      "Purpose": "Fund the org's runway",
      "Accountabilities": "Prospect pipeline; grant reporting; Founder's Council program; House Party kit",
      "Scope": "Major gifts, foundations, dues, events",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Rohan",
      "Person ID": "P-001",
      "Definition note": "Renamed from Fundraising & Development Circle on 2026-09-22.",
      "Engagement level": "Staff",
      "Assignment basis": "User-directed default assignment"
    },
    {
      "ID": "G-020",
      "Name": "House Party Fundraising Operations",
      "Type": "Role",
      "Parent Circle ID": "G-036",
      "Purpose": "Hosts have reliable tools and processes for running effective fundraising gatherings.",
      "Accountabilities": "Maintaining host kits and registration workflows; coordinating donation tracking and follow-up automations; supporting hosts; reviewing operational results with fundraising",
      "Scope": "House-party systems, host support, and follow-up workflows",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Pe",
      "Person ID": "P-010",
      "Definition note": " Updated from user-directed governance and role definitions on 2026-09-23.",
      "Engagement level": "Fellow",
      "Assignment basis": "User-provided project match"
    },
    {
      "ID": "G-021",
      "Name": "Advocacy Circle Lead",
      "Type": "Role",
      "Parent Circle ID": "G-007",
      "Purpose": "Advocacy efforts have clear priorities, roles, and resources.",
      "Accountabilities": "Prioritizing advocacy work; maintaining role assignments; allocating available resources; resolving priority conflicts across campaigns",
      "Scope": "",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Rohan",
      "Person ID": "P-001",
      "Definition note": "Named as an owner in the original work register; no matching governance definition. Original label: Advocacy Circle Lead. Parent circle set to Advocacy Circle (G-007): exact name match. Updated from user-directed governance and role definitions on 2026-09-23.",
      "Engagement level": "Staff",
      "Assignment basis": "User-directed default assignment"
    },
    {
      "ID": "G-022",
      "Name": "Community Circle Lead",
      "Type": "Role",
      "Parent Circle ID": "G-010",
      "Purpose": "People can join, participate, and build lasting local and global community.",
      "Accountabilities": "Prioritizing community work; coordinating member participation and chapter-support resources; maintaining role assignments; reviewing participation needs",
      "Scope": "",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Rohan",
      "Person ID": "P-001",
      "Definition note": "Named as an owner in the original work register; no matching governance definition. Original label: Community Circle Lead. Parent circle set to Community Circle (G-010): exact name match. Updated from user-directed governance and role definitions on 2026-09-23.",
      "Engagement level": "Staff",
      "Assignment basis": "User-directed default assignment"
    },
    {
      "ID": "G-023",
      "Name": "Empowerment Circle Lead",
      "Type": "Role",
      "Parent Circle ID": "G-013",
      "Purpose": "Members develop the knowledge and leadership to take responsibility for movement work.",
      "Accountabilities": "Prioritizing learning and development; coordinating training and fellowship support; maintaining role assignments; identifying capacity gaps",
      "Scope": "",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Rohan",
      "Person ID": "P-001",
      "Definition note": "Named as an owner in the original work register; no matching governance definition. Original label: Empowerment Circle Lead. Parent circle set to Empowerment Circle (G-013): exact name match. Updated from user-directed governance and role definitions on 2026-09-23.",
      "Engagement level": "Staff",
      "Assignment basis": "User-directed default assignment"
    },
    {
      "ID": "G-024",
      "Name": "Stop 1984! Circle Lead",
      "Type": "Role",
      "Parent Circle ID": "G-008",
      "Purpose": "",
      "Accountabilities": "",
      "Scope": "",
      "Privileges": "",
      "Status": "Retired",
      "Lead Link": "",
      "Person ID": "",
      "Definition note": "Named as an owner in the original work register; no matching governance definition. Original label: Stop 1984! Circle Lead (Al). Parent circle set to Stop 1984! Circle (G-008): exact name match. Retired 2026-09-23: Stop 1984 campaign responsibility consolidated into Stop 1984 CA Strategist (G-009).",
      "Engagement level": "",
      "Assignment basis": ""
    },
    {
      "ID": "G-025",
      "Name": "Chapter Network Circle Lead",
      "Type": "Role",
      "Parent Circle ID": "G-011",
      "Purpose": "",
      "Accountabilities": "",
      "Scope": "",
      "Privileges": "",
      "Status": "Retired",
      "Lead Link": "",
      "Person ID": "",
      "Definition note": "Named as an owner in the original work register; no matching governance definition. Original label: Chapter Network Circle Lead. Parent circle set to Chapter Network Circle (G-011): exact name match. Retired 2026-09-23: Chapter Network role removed; continuing chapter-support work belongs to Community Circle Lead.",
      "Engagement level": "",
      "Assignment basis": ""
    },
    {
      "ID": "G-026",
      "Name": "Fellowship Coordinator",
      "Type": "Role",
      "Parent Circle ID": "G-013",
      "Purpose": "Fellows contribute meaningfully and develop the capacity to own work.",
      "Accountabilities": "Coordinating recruitment and onboarding; matching Fellows to roles and projects; conducting check-ins; supporting program expansion; coordinating graduation reviews after three months",
      "Scope": "Fellowship operations, role matching, and graduation process",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Rohan",
      "Person ID": "P-001",
      "Definition note": "Named as an owner in the original work register; no matching governance definition. Original label: Fellowship Program Lead. Parent circle set to Fellowship Program Circle (G-014): matching name. Merged with G-014 on 2026-09-23; continuing role retains its ID and work ownership. Purpose, accountabilities, scope, privileges, and recorded assignment carried forward from the wrapper. Updated from user-directed governance and role definitions on 2026-09-23.",
      "Engagement level": "Staff",
      "Assignment basis": "User-directed default assignment"
    },
    {
      "ID": "G-027",
      "Name": "Communications Coordinator",
      "Type": "Role",
      "Parent Circle ID": "G-004",
      "Purpose": "People understand the movement and receive coherent, useful communications.",
      "Accountabilities": "Coordinating messaging across channels; maintaining email and SMS plans; scheduling participant communications; collecting feedback and reviewing engagement",
      "Scope": "Cross-channel communications planning",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Rohan",
      "Person ID": "P-001",
      "Definition note": "Named as an owner in the original work register; no matching governance definition. Original label: Marketing & Communications Circle Lead. No governance circle named \"Marketing & Communications\" exists (closest is Communications & Narrative Circle, G-004); left unassigned pending explicit reconciliation, per the Website/Marketing & Communications naming mismatch already noted for D-013. Updated from user-directed governance and role definitions on 2026-09-23.",
      "Engagement level": "Staff",
      "Assignment basis": "User-directed default assignment"
    },
    {
      "ID": "G-028",
      "Name": "Finance & Fundraising Lead",
      "Type": "Role",
      "Parent Circle ID": "G-019",
      "Purpose": "The movement has dependable financial support for its strategy.",
      "Accountabilities": "Maintaining fundraising priorities and the funding pipeline; coordinating financial planning and reporting; reviewing resource needs; supporting fundraising initiatives",
      "Scope": "",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Rohan",
      "Person ID": "P-001",
      "Definition note": "Named as an owner in the original work register; no matching governance definition. Original label: Fundraising & Development Circle Lead. Parent circle set to Fundraising & Development Circle (G-019): exact name match. Updated from user-directed governance and role definitions on 2026-09-23.",
      "Engagement level": "Staff",
      "Assignment basis": "User-directed default assignment"
    },
    {
      "ID": "G-029",
      "Name": "Operations Lead",
      "Type": "Role",
      "Parent Circle ID": "G-017",
      "Purpose": "Shared operational processes let the movement work reliably.",
      "Accountabilities": "Maintaining operating processes and records; coordinating budget and administrative work; identifying operational bottlenecks; supporting clear project and role management",
      "Scope": "",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Rohan",
      "Person ID": "P-001",
      "Definition note": "Named as an owner in the original work register; no matching governance definition. Original label: Operations & Infrastructure Circle Lead. Parent circle set to Operations & Infrastructure Circle (G-017): exact name match. Updated from user-directed governance and role definitions on 2026-09-23.",
      "Engagement level": "Staff",
      "Assignment basis": "User-directed default assignment"
    },
    {
      "ID": "G-030",
      "Name": "Knowledge Base",
      "Type": "Role",
      "Parent Circle ID": "G-013",
      "Purpose": "Members can find clear, current resources explaining why and how to participate.",
      "Accountabilities": "Curating the Resource Center; organizing and reviewing guidance; coordinating content contributions; identifying missing or outdated knowledge",
      "Scope": "Knowledge content, navigation, and editorial organization",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Da",
      "Person ID": "P-005",
      "Definition note": "Named as an owner in the original work register; no matching governance definition. Original label: Knowledge Base Steward (Da). Parent circle set to Knowledge Base Circle (G-015): matching name, corroborated by Da also being its recorded Lead Link. Merged with G-015 on 2026-09-23; continuing role retains its ID and work ownership. Purpose, accountabilities, scope, privileges, and recorded assignment carried forward from the wrapper. Tech (G-036) also consolidated on 2026-09-23 after the Knowledge Base merge left it with only this role; no additional definition or assignment was inferred. Updated from user-directed governance and role definitions on 2026-09-23.",
      "Engagement level": "Fellow",
      "Assignment basis": "User-provided project match"
    },
    {
      "ID": "G-031",
      "Name": "Membership Systems",
      "Type": "Role",
      "Parent Circle ID": "G-036",
      "Purpose": "Supporters can join and participate through reliable membership workflows.",
      "Accountabilities": "Maintaining registration and onboarding automations; connecting payment, CRM, and community systems; monitoring failures; maintaining documented data and access practices",
      "Scope": "Membership integrations and lifecycle automation",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Ba",
      "Person ID": "P-008",
      "Definition note": "Named as an owner in the original work register; no matching governance definition. Original label: Membership Systems Lead (Ba). Parent circle set to Membership Systems Circle (G-018): matching name, corroborated by Ba also being its recorded Lead Link. Merged with G-018 on 2026-09-23; continuing role retains its ID and work ownership. Purpose, accountabilities, scope, privileges, and recorded assignment carried forward from the wrapper. Updated from user-directed governance and role definitions on 2026-09-23.",
      "Engagement level": "Fellow",
      "Assignment basis": "User-provided project match"
    },
    {
      "ID": "G-032",
      "Name": "House Party Program Lead",
      "Type": "Role",
      "Parent Circle ID": "",
      "Purpose": "",
      "Accountabilities": "",
      "Scope": "",
      "Privileges": "",
      "Status": "Retired",
      "Lead Link": "",
      "Person ID": "",
      "Definition note": "Named as an owner in the original work register; no matching governance definition. Original label: House Party Program Lead (Pe). Possible duplicate of House Party Program (G-020, Role under G-019, Lead Link Pe); left unassigned pending explicit reconciliation rather than merged. Retired 2026-09-23: Duplicate house-party role consolidated into House Party Fundraising Operations (G-020).",
      "Engagement level": "",
      "Assignment basis": ""
    },
    {
      "ID": "G-033",
      "Name": "Social Media Manager",
      "Type": "Role",
      "Parent Circle ID": "G-004",
      "Purpose": "People encounter, follow, and share the movement through its social channels.",
      "Accountabilities": "Maintaining the social content calendar; publishing and coordinating channel content; monitoring engagement; improving distribution and channel workflows",
      "Scope": "Social channels and publishing workflow",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Rohan",
      "Person ID": "P-001",
      "Definition note": "Named as an owner in the original work register; no matching governance definition. Original label: Digital Presence Lead. Parent circle set to Digital Presence Circle (G-012): matching name. Merged with G-012 on 2026-09-23; continuing role retains its ID and work ownership. Purpose, accountabilities, scope, privileges, and recorded assignment carried forward from the wrapper. Updated from user-directed governance and role definitions on 2026-09-23.",
      "Engagement level": "Staff",
      "Assignment basis": "User-directed default assignment"
    },
    {
      "ID": "G-034",
      "Name": "Newspaper Editor-in-Chief",
      "Type": "Role",
      "Parent Circle ID": "G-010",
      "Purpose": "The newspaper keeps members informed, connected, and engaged.",
      "Accountabilities": "Planning issues and publication cadence; soliciting and editing contributions; maintaining editorial standards; coordinating publication and distribution",
      "Scope": "Newspaper editorial process and production",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Vi",
      "Person ID": "P-009",
      "Definition note": "Named as an owner in the original work register; no matching governance definition. Original label: Editor-in-Chief (Vi). Likely belongs under Newspaper Circle (G-016, Lead Link Vi), but the name itself doesn't reference a circle; left unassigned pending explicit reconciliation. Updated from user-directed governance and role definitions on 2026-09-23.",
      "Engagement level": "Fellow",
      "Assignment basis": "User-provided project match"
    },
    {
      "ID": "G-035",
      "Name": "Secretary",
      "Type": "Role",
      "Parent Circle ID": "G-001",
      "Purpose": "Organizational records and meeting outcomes remain clear and accessible.",
      "Accountabilities": "Maintaining governance records; recording decisions and meeting outputs; coordinating general-meeting documentation; keeping published role information current",
      "Scope": "Organization-wide records and meeting documentation",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Rohan",
      "Person ID": "P-001",
      "Definition note": "Named as an owner in the original work register; no matching governance definition. Original label: Secretary. No corresponding circle name or owner correlation found; left unassigned pending explicit reconciliation. Updated from user-directed governance and role definitions on 2026-09-23.",
      "Engagement level": "Staff",
      "Assignment basis": "User-directed default assignment"
    },
    {
      "ID": "G-036",
      "Name": "Tech",
      "Type": "Circle",
      "Parent Circle ID": "G-001",
      "Purpose": "Reliable tools and automations support the movement’s operations.",
      "Accountabilities": "Maintaining shared technical systems; coordinating system ownership and improvements; tracking reliability and access needs",
      "Scope": "",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Rohan",
      "Person ID": "P-001",
      "Definition note": "Added 2026-09-22 as a new top-level circle; takes over Knowledge Base Circle (G-015) from Empowerment. Purpose/Accountabilities/Scope not yet documented. Retired 2026-09-23: after Knowledge Base consolidation, its only child was G-030. The continuing role now sits in Sapiens First Global. Updated from user-directed governance and role definitions on 2026-09-23.",
      "Engagement level": "Staff",
      "Assignment basis": "User-directed default assignment"
    },
    {
      "ID": "G-037",
      "Name": "Stop 1984 Background Researcher",
      "Type": "Role",
      "Parent Circle ID": "G-007",
      "Purpose": "The campaign has a credible, accessible foundation of historical and policy research.",
      "Accountabilities": "Gathering and checking source material; maintaining the campaign research brief; answering agreed research questions; sharing findings with strategy and policy roles",
      "Scope": "Stop 1984 history and background research",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Ma",
      "Person ID": "P-002",
      "Definition note": "Added 2026-09-22 under Advocacy Circle. Purpose/Accountabilities not yet documented. Updated from user-directed governance and role definitions on 2026-09-23.",
      "Engagement level": "Fellow",
      "Assignment basis": "User-provided project match"
    },
    {
      "ID": "G-038",
      "Name": "Stop 1984 Policy Ask Creator",
      "Type": "Role",
      "Parent Circle ID": "G-007",
      "Purpose": "The campaign communicates specific and well-supported policy asks.",
      "Accountabilities": "Drafting policy asks; researching policy options and decision-makers; incorporating campaign research and coalition feedback; maintaining clear supporting arguments",
      "Scope": "Stop 1984 policy asks and supporting briefs",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Ca",
      "Person ID": "P-003",
      "Definition note": "Added 2026-09-22 under Advocacy Circle. Purpose/Accountabilities not yet documented. Updated from user-directed governance and role definitions on 2026-09-23.",
      "Engagement level": "Fellow",
      "Assignment basis": "User-provided project match"
    },
    {
      "ID": "G-039",
      "Name": "No Killer Robots Campaigner",
      "Type": "Role",
      "Parent Circle ID": "G-007",
      "Purpose": "Support grows for regulating deadly autonomous weapons.",
      "Accountabilities": "Developing campaign framing and policy arguments; mapping supporters and audiences; coordinating outreach and campaign materials; reviewing campaign opportunities",
      "Scope": "No Killer Robots policy and public-support campaign",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Al",
      "Person ID": "P-007",
      "Definition note": "Added 2026-09-22 under Advocacy Circle. Purpose/Accountabilities not yet documented. Updated from user-directed governance and role definitions on 2026-09-23.",
      "Engagement level": "Fellow",
      "Assignment basis": "User-provided project match"
    },
    {
      "ID": "G-040",
      "Name": "Campaign Support Strategist",
      "Type": "Role",
      "Parent Circle ID": "G-007",
      "Purpose": "Campaign teams have practical tools and priorities for effective execution.",
      "Accountabilities": "Maintaining the Campaign Execution Toolkit; helping teams break down and prioritize projects; identifying campaign-support gaps; sharing effective organizing practices",
      "Scope": "Campaign support methods and execution toolkit",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Rohan",
      "Person ID": "P-001",
      "Definition note": "Added 2026-09-22 under Advocacy Circle. Purpose/Accountabilities not yet documented. Updated from user-directed governance and role definitions on 2026-09-23.",
      "Engagement level": "Staff",
      "Assignment basis": "User-directed default assignment"
    },
    {
      "ID": "G-041",
      "Name": "DNA",
      "Type": "Circle",
      "Parent Circle ID": "G-001",
      "Purpose": "The movement has a coherent direction and the resources to pursue it.",
      "Accountabilities": "Integrating movement strategy and financial planning; reviewing progress toward organizational goals; maintaining shared priorities",
      "Scope": "",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Rohan",
      "Person ID": "P-001",
      "Definition note": "Created 2026-09-23 to contain Vision & Strategy and Finance & Fundraising; assignment not yet recorded. Updated from user-directed governance and role definitions on 2026-09-23.",
      "Engagement level": "Staff",
      "Assignment basis": "User-directed default assignment"
    },
    {
      "ID": "G-042",
      "Name": "Berkeley Chapter",
      "Type": "Circle",
      "Parent Circle ID": "",
      "Purpose": "A locally rooted Berkeley community advances the movement’s mission.",
      "Accountabilities": "Organizing local participation and gatherings; developing local organizing capacity; coordinating chapter activities and sharing learning with the wider movement",
      "Scope": "",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Rohan",
      "Person ID": "P-001",
      "Definition note": " Updated from user-directed governance and role definitions on 2026-09-23.",
      "Engagement level": "Staff",
      "Assignment basis": "User-directed default assignment"
    },
    {
      "ID": "G-043",
      "Name": "Knowledge Management System Steward",
      "Type": "Role",
      "Parent Circle ID": "G-036",
      "Purpose": "The knowledge platform is reliable, usable, and maintainable.",
      "Accountabilities": "Maintaining the knowledge-management platform and integrations; managing documented access and backup processes; resolving technical issues; supporting content contributors",
      "Scope": "Knowledge platform configuration and technical maintenance",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Da",
      "Person ID": "P-005",
      "Definition note": " Updated from user-directed governance and role definitions on 2026-09-23.",
      "Engagement level": "Fellow",
      "Assignment basis": "User-provided project match"
    },
    {
      "ID": "G-044",
      "Name": "Campaign Media Producer",
      "Type": "Role",
      "Parent Circle ID": "G-004",
      "Purpose": "Campaign organizers have clear, usable media resources.",
      "Accountabilities": "Developing Stop 1984 campaign media resources; adapting research and policy asks into public-facing materials; coordinating visual and editorial consistency; maintaining reusable campaign assets",
      "Scope": "Campaign media resource development",
      "Privileges": "",
      "Status": "Active",
      "Lead Link": "Ab",
      "Person ID": "P-006",
      "Definition note": " Updated from user-directed governance and role definitions on 2026-09-23.",
      "Engagement level": "Fellow",
      "Assignment basis": "User-provided project match"
    }
  ],
  "relationships": [
    {
      "ID": "R-001",
      "From ID": "G-002",
      "Relationship": "owns",
      "To ID": "D-001",
      "Valid from": "",
      "Valid until": "",
      "Notes": "Imported ownership; start date not recorded."
    },
    {
      "ID": "R-002",
      "From ID": "G-021",
      "Relationship": "owns",
      "To ID": "D-002",
      "Valid from": "",
      "Valid until": "",
      "Notes": "Imported ownership; start date not recorded."
    },
    {
      "ID": "R-003",
      "From ID": "G-022",
      "Relationship": "owns",
      "To ID": "D-003",
      "Valid from": "",
      "Valid until": "",
      "Notes": "Imported ownership; start date not recorded."
    },
    {
      "ID": "R-004",
      "From ID": "G-023",
      "Relationship": "owns",
      "To ID": "D-004",
      "Valid from": "",
      "Valid until": "",
      "Notes": "Imported ownership; start date not recorded."
    },
    {
      "ID": "R-005",
      "From ID": "G-024",
      "Relationship": "owns",
      "To ID": "D-005",
      "Valid from": "",
      "Valid until": "2026-09-23",
      "Notes": "Imported ownership; start date not recorded."
    },
    {
      "ID": "R-006",
      "From ID": "G-025",
      "Relationship": "owns",
      "To ID": "D-006",
      "Valid from": "",
      "Valid until": "2026-09-23",
      "Notes": "Imported ownership; start date not recorded."
    },
    {
      "ID": "R-007",
      "From ID": "G-026",
      "Relationship": "owns",
      "To ID": "D-007",
      "Valid from": "",
      "Valid until": "",
      "Notes": "Imported ownership; start date not recorded."
    },
    {
      "ID": "R-008",
      "From ID": "G-023",
      "Relationship": "owns",
      "To ID": "D-008",
      "Valid from": "",
      "Valid until": "",
      "Notes": "Imported ownership; start date not recorded."
    },
    {
      "ID": "R-009",
      "From ID": "G-027",
      "Relationship": "owns",
      "To ID": "D-009",
      "Valid from": "",
      "Valid until": "",
      "Notes": "Imported ownership; start date not recorded."
    },
    {
      "ID": "R-010",
      "From ID": "G-028",
      "Relationship": "owns",
      "To ID": "D-010",
      "Valid from": "",
      "Valid until": "",
      "Notes": "Imported ownership; start date not recorded."
    },
    {
      "ID": "R-011",
      "From ID": "G-029",
      "Relationship": "owns",
      "To ID": "D-011",
      "Valid from": "",
      "Valid until": "",
      "Notes": "Imported ownership; start date not recorded."
    },
    {
      "ID": "R-012",
      "From ID": "G-005",
      "Relationship": "owns",
      "To ID": "D-012",
      "Valid from": "",
      "Valid until": "",
      "Notes": "Imported ownership; start date not recorded."
    },
    {
      "ID": "R-013",
      "From ID": "G-006",
      "Relationship": "owns",
      "To ID": "D-013",
      "Valid from": "",
      "Valid until": "",
      "Notes": "Imported ownership; start date not recorded."
    },
    {
      "ID": "R-014",
      "From ID": "G-030",
      "Relationship": "owns",
      "To ID": "D-014",
      "Valid from": "",
      "Valid until": "",
      "Notes": "Imported ownership; start date not recorded."
    },
    {
      "ID": "R-015",
      "From ID": "G-031",
      "Relationship": "owns",
      "To ID": "D-015",
      "Valid from": "",
      "Valid until": "",
      "Notes": "Imported ownership; start date not recorded."
    },
    {
      "ID": "R-016",
      "From ID": "G-032",
      "Relationship": "owns",
      "To ID": "D-016",
      "Valid from": "",
      "Valid until": "2026-09-23",
      "Notes": "Imported ownership; start date not recorded."
    },
    {
      "ID": "R-017",
      "From ID": "G-033",
      "Relationship": "owns",
      "To ID": "D-017",
      "Valid from": "",
      "Valid until": "",
      "Notes": "Imported ownership; start date not recorded."
    },
    {
      "ID": "R-018",
      "From ID": "G-034",
      "Relationship": "owns",
      "To ID": "D-018",
      "Valid from": "",
      "Valid until": "",
      "Notes": "Imported ownership; start date not recorded."
    },
    {
      "ID": "R-019",
      "From ID": "G-025",
      "Relationship": "owns",
      "To ID": "D-019",
      "Valid from": "",
      "Valid until": "2026-09-23",
      "Notes": "Imported ownership; start date not recorded."
    },
    {
      "ID": "R-020",
      "From ID": "G-035",
      "Relationship": "owns",
      "To ID": "D-020",
      "Valid from": "",
      "Valid until": "",
      "Notes": "Imported ownership; start date not recorded."
    },
    {
      "ID": "R-021",
      "From ID": "G-037",
      "Relationship": "owns",
      "To ID": "D-024",
      "Valid from": "",
      "Valid until": "",
      "Notes": "Added 2026-09-22 per governance restructuring."
    },
    {
      "ID": "R-022",
      "From ID": "G-037",
      "Relationship": "owns",
      "To ID": "D-025",
      "Valid from": "",
      "Valid until": "2026-09-23",
      "Notes": "Added 2026-09-22 per governance restructuring."
    },
    {
      "ID": "R-023",
      "From ID": "G-038",
      "Relationship": "owns",
      "To ID": "D-026",
      "Valid from": "",
      "Valid until": "",
      "Notes": "Added 2026-09-22 per governance restructuring."
    },
    {
      "ID": "R-024",
      "From ID": "G-038",
      "Relationship": "owns",
      "To ID": "D-027",
      "Valid from": "",
      "Valid until": "2026-09-23",
      "Notes": "Added 2026-09-22 per governance restructuring."
    },
    {
      "ID": "R-025",
      "From ID": "G-039",
      "Relationship": "owns",
      "To ID": "D-028",
      "Valid from": "",
      "Valid until": "",
      "Notes": "Added 2026-09-22 per governance restructuring."
    },
    {
      "ID": "R-026",
      "From ID": "G-040",
      "Relationship": "owns",
      "To ID": "D-029",
      "Valid from": "",
      "Valid until": "2026-09-23",
      "Notes": "Added 2026-09-22 per governance restructuring."
    },
    {
      "ID": "R-027",
      "From ID": "G-002",
      "Relationship": "succeeds",
      "To ID": "G-003",
      "Valid from": "2026-09-23",
      "Valid until": "",
      "Notes": "Single-role circle consolidated into its continuing role by user direction; existing role ownership retained."
    },
    {
      "ID": "R-028",
      "From ID": "G-033",
      "Relationship": "succeeds",
      "To ID": "G-012",
      "Valid from": "2026-09-23",
      "Valid until": "",
      "Notes": "Single-role circle consolidated into its continuing role by user direction; existing role ownership retained."
    },
    {
      "ID": "R-029",
      "From ID": "G-026",
      "Relationship": "succeeds",
      "To ID": "G-014",
      "Valid from": "2026-09-23",
      "Valid until": "",
      "Notes": "Single-role circle consolidated into its continuing role by user direction; existing role ownership retained."
    },
    {
      "ID": "R-030",
      "From ID": "G-030",
      "Relationship": "succeeds",
      "To ID": "G-015",
      "Valid from": "2026-09-23",
      "Valid until": "",
      "Notes": "Single-role circle consolidated into its continuing role by user direction; existing role ownership retained."
    },
    {
      "ID": "R-031",
      "From ID": "G-031",
      "Relationship": "succeeds",
      "To ID": "G-018",
      "Valid from": "2026-09-23",
      "Valid until": "",
      "Notes": "Single-role circle consolidated into its continuing role by user direction; existing role ownership retained."
    },
    {
      "ID": "R-032",
      "From ID": "G-030",
      "Relationship": "succeeds",
      "To ID": "G-036",
      "Valid from": "2026-09-23",
      "Valid until": "",
      "Notes": "Tech contained only the continuing Knowledge Base role after consolidation; apply the single-role-circle rule recursively. Subsequently reversed by user direction: Tech restored as its own circle on 2026-09-23."
    },
    {
      "ID": "R-033",
      "From ID": "G-009",
      "Relationship": "owns",
      "To ID": "D-005",
      "Valid from": "2026-09-23",
      "Valid until": "",
      "Notes": "User-directed role responsibility and default assignment refinement."
    },
    {
      "ID": "R-034",
      "From ID": "G-022",
      "Relationship": "owns",
      "To ID": "D-006",
      "Valid from": "2026-09-23",
      "Valid until": "",
      "Notes": "User-directed role responsibility and default assignment refinement."
    },
    {
      "ID": "R-035",
      "From ID": "G-020",
      "Relationship": "owns",
      "To ID": "D-016",
      "Valid from": "2026-09-23",
      "Valid until": "",
      "Notes": "User-directed role responsibility and default assignment refinement."
    },
    {
      "ID": "R-036",
      "From ID": "G-022",
      "Relationship": "owns",
      "To ID": "D-019",
      "Valid from": "2026-09-23",
      "Valid until": "",
      "Notes": "User-directed role responsibility and default assignment refinement."
    },
    {
      "ID": "R-037",
      "From ID": "G-026",
      "Relationship": "owns",
      "To ID": "D-021",
      "Valid from": "2026-09-23",
      "Valid until": "",
      "Notes": "User-directed role responsibility and default assignment refinement."
    },
    {
      "ID": "R-038",
      "From ID": "G-021",
      "Relationship": "owns",
      "To ID": "D-022",
      "Valid from": "2026-09-23",
      "Valid until": "",
      "Notes": "User-directed role responsibility and default assignment refinement."
    },
    {
      "ID": "R-039",
      "From ID": "G-039",
      "Relationship": "owns",
      "To ID": "D-023",
      "Valid from": "2026-09-23",
      "Valid until": "",
      "Notes": "User-directed role responsibility and default assignment refinement."
    },
    {
      "ID": "R-040",
      "From ID": "G-021",
      "Relationship": "owns",
      "To ID": "D-025",
      "Valid from": "2026-09-23",
      "Valid until": "",
      "Notes": "User-directed role responsibility and default assignment refinement."
    },
    {
      "ID": "R-041",
      "From ID": "G-021",
      "Relationship": "owns",
      "To ID": "D-027",
      "Valid from": "2026-09-23",
      "Valid until": "",
      "Notes": "User-directed role responsibility and default assignment refinement."
    },
    {
      "ID": "R-042",
      "From ID": "G-009",
      "Relationship": "owns",
      "To ID": "D-029",
      "Valid from": "2026-09-23",
      "Valid until": "",
      "Notes": "User-directed role responsibility and default assignment refinement."
    },
    {
      "ID": "R-043",
      "From ID": "G-044",
      "Relationship": "owns",
      "To ID": "D-030",
      "Valid from": "2026-09-23",
      "Valid until": "",
      "Notes": "User-directed role responsibility and default assignment refinement."
    },
    {
      "ID": "R-044",
      "From ID": "G-002",
      "Relationship": "owns",
      "To ID": "D-031",
      "Valid from": "2026-09-23",
      "Valid until": "",
      "Notes": "User-directed role responsibility and default assignment refinement."
    },
    {
      "ID": "R-045",
      "From ID": "G-002",
      "Relationship": "owns",
      "To ID": "D-032",
      "Valid from": "2026-09-23",
      "Valid until": "",
      "Notes": "User-directed role responsibility and default assignment refinement."
    },
    {
      "ID": "R-046",
      "From ID": "G-021",
      "Relationship": "owns",
      "To ID": "D-033",
      "Valid from": "2026-09-23",
      "Valid until": "",
      "Notes": "User-directed role responsibility and default assignment refinement."
    },
    {
      "ID": "R-047",
      "From ID": "G-040",
      "Relationship": "owns",
      "To ID": "D-034",
      "Valid from": "2026-09-23",
      "Valid until": "",
      "Notes": "User-directed role responsibility and default assignment refinement."
    },
    {
      "ID": "R-048",
      "From ID": "G-040",
      "Relationship": "owns",
      "To ID": "D-035",
      "Valid from": "2026-09-23",
      "Valid until": "",
      "Notes": "User-directed role responsibility and default assignment refinement."
    },
    {
      "ID": "R-049",
      "From ID": "G-022",
      "Relationship": "owns",
      "To ID": "D-036",
      "Valid from": "2026-09-23",
      "Valid until": "",
      "Notes": "User-directed role responsibility and default assignment refinement."
    },
    {
      "ID": "R-050",
      "From ID": "G-030",
      "Relationship": "owns",
      "To ID": "D-037",
      "Valid from": "2026-09-23",
      "Valid until": "",
      "Notes": "User-directed role responsibility and default assignment refinement."
    },
    {
      "ID": "R-051",
      "From ID": "G-023",
      "Relationship": "owns",
      "To ID": "D-038",
      "Valid from": "2026-09-23",
      "Valid until": "",
      "Notes": "User-directed role responsibility and default assignment refinement."
    },
    {
      "ID": "R-052",
      "From ID": "G-029",
      "Relationship": "owns",
      "To ID": "D-039",
      "Valid from": "2026-09-23",
      "Valid until": "",
      "Notes": "User-directed role responsibility and default assignment refinement."
    },
    {
      "ID": "R-053",
      "From ID": "G-026",
      "Relationship": "owns",
      "To ID": "D-040",
      "Valid from": "2026-09-23",
      "Valid until": "",
      "Notes": "User-directed role responsibility and default assignment refinement."
    },
    {
      "ID": "R-054",
      "From ID": "G-040",
      "Relationship": "owns",
      "To ID": "D-041",
      "Valid from": "2026-09-23",
      "Valid until": "",
      "Notes": "User-directed role responsibility and default assignment refinement."
    },
    {
      "ID": "R-055",
      "From ID": "G-043",
      "Relationship": "owns",
      "To ID": "D-042",
      "Valid from": "2026-09-23",
      "Valid until": "",
      "Notes": "User-directed role responsibility and default assignment refinement."
    },
    {
      "ID": "R-056",
      "From ID": "G-034",
      "Relationship": "succeeds",
      "To ID": "G-016",
      "Valid from": "2026-09-23",
      "Valid until": "",
      "Notes": "User-directed consolidation into a continuing role."
    },
    {
      "ID": "R-057",
      "From ID": "G-009",
      "Relationship": "succeeds",
      "To ID": "G-008",
      "Valid from": "2026-09-23",
      "Valid until": "",
      "Notes": "User-directed consolidation into a continuing role."
    },
    {
      "ID": "R-058",
      "From ID": "G-009",
      "Relationship": "succeeds",
      "To ID": "G-024",
      "Valid from": "2026-09-23",
      "Valid until": "",
      "Notes": "User-directed consolidation into a continuing role."
    },
    {
      "ID": "R-059",
      "From ID": "G-020",
      "Relationship": "succeeds",
      "To ID": "G-032",
      "Valid from": "2026-09-23",
      "Valid until": "",
      "Notes": "User-directed consolidation into a continuing role."
    }
  ]
};
