export type Principle = { title: string; text: string };

/** The eight principles, grouped by pillar: Life, Liberty, the pursuit of Happiness. */
export const charterPrinciples: Principle[][] = [
  [
    {
      title: "A Coordinated Slowdown",
      text: "An international agreement that paces the development of frontier intelligence.",
    },
    {
      title: "A Global Initiative for Superalignment",
      text: "Let the great powers of the world work together to accelerate the alignment of AI to the collective interests of humanity.",
    },
  ],
  [
    {
      title: "A Human-First Government",
      text: "End corporate capture to put human interests first in our government.",
    },
    {
      title: "Renewed Checks and Balances",
      text: "Transparency and accountability on the concentration of power from superintelligence and autonomous machines.",
    },
    {
      title: "Enhance Civic Input",
      text: "Use information technology to facilitate civic communication and democracy, rather than political polarization.",
    },
  ],
  [
    {
      title: "Institutional Reform",
      text: "Radical transformation of our institutions to eradicate bureaucracy and enhance the functioning of the public sector.",
    },
    {
      title: "The Citizen's Dividend",
      text: "Distribute the economic power generated by abundant intelligence to the world's people.",
    },
    {
      title: "Uplift All Sentient Beings",
      text: "Unleash the powers of technology to protect — not harm — non-human animals and other sentient beings.",
    },
  ],
];
